;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_DirList
	.export		_FileExists
	.import		_fileNum
	.import		_fileNames
	.export		_CompareNames

; ---------------------------------------------------------------
; unsigned char __near__ FileExists (const char *fname)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_FileExists: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     M0001
	jsr     _DirList
	jmp     L0004
L0002:	jsr     pushw0sp
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L0007
	inx
	clc
L0007:	adc     #<(_fileNames)
	tay
	txa
	adc     #>(_fileNames)
	tax
	tya
	jsr     ldaxi
	jsr     _CompareNames
	tax
	bne     L0005
	lda     #$01
	jmp     incsp2
L0005:	inc     M0001
L0004:	lda     M0001
	cmp     _fileNum
	bcc     L0002
	ldx     #$00
	txa
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ CompareNames (const char *fname1, const char *fname2)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CompareNames: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     M0001
L0002:	ldy     #$03
	jsr     ldaxysp
	ldy     M0001
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0002
	jsr     ldax0sp
	ldy     M0001
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0003
	lda     M0002
	bne     L0012
	lda     M0003
	bne     L0012
	tax
	jmp     incsp4
L0012:	lda     M0002
	cmp     #$C1
	bcc     L0013
	sec
	sbc     #$80
	sta     M0002
L0013:	lda     M0003
	cmp     #$C1
	bcc     L0014
	sec
	sbc     #$80
	sta     M0003
L0014:	lda     M0002
	cmp     #$61
	bcc     L0015
	sec
	sbc     #$20
	sta     M0002
L0015:	lda     M0003
	cmp     #$61
	ldx     #$00
	bcc     L0016
	lda     M0003
	sec
	sbc     #$20
	sta     M0003
L0016:	lda     M0002
	cmp     M0003
	bne     L0017
	inc     M0001
	jmp     L0002
L0017:	lda     M0001
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00

.endproc

