;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_txtY
	.import		_PrintStr
	.export		_Button
	.import		_PushCallback

; ---------------------------------------------------------------
; struct $anon-struct-0019 *__near__ Button (unsigned char col, unsigned char row, unsigned char width, unsigned char height, unsigned char *label)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_Button: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$05
	lda     (c_sp),y
	sta     _txtX
	dey
	lda     (c_sp),y
	sta     _txtY
	jsr     ldax0sp
	jsr     _PrintStr
	ldy     #$05
	lda     (c_sp),y
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	jsr     pusha
	lda     #$02
	jsr     _PushCallback
	jmp     incsp6

.endproc

