;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_txtY
	.import		_inkColor
	.import		_paperColor
	.import		_PrintChr
	.import		_PrintStr
	.export		_CheckCallbacks
	.import		_SliderPos
	.import		_inputCall
	.import		_inputWidth
	.export		_callHead
	.export		_callList

.segment	"DATA"

_callHead:
	.word	$0000
_callList:
	.word	$0000

; ---------------------------------------------------------------
; struct $anon-struct-0019 *__near__ CheckCallbacks (unsigned char col, unsigned char row)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_CheckCallbacks: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     _callHead+1
	sta     M0001+1
	lda     _callHead
	sta     M0001
	jmp     L0004
L0002:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	iny
	cmp     (c_sp),y
	beq     L001F
	jcs     L0005
L001F:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     (ptr1),y
	cmp     (c_sp),y
	jcc     L0005
	jeq     L0005
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	iny
	lda     (ptr1),y
	ldy     #$00
	cmp     (c_sp),y
	beq     L0020
	jcs     L0005
L0020:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	ldy     #$00
	cmp     (c_sp),y
	jeq     L0005
	jcc     L0005
	lda     _inkColor
	sta     M0004
	lda     _paperColor
	sta     M0005
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	cmp     #$03
	beq     L000B
	cmp     #$04
	beq     L000C
	cmp     #$05
	jeq     L000E
	jmp     L0025
L000B:	lda     M0001+1
	sta     _inputCall+1
	lda     M0001
	sta     _inputCall
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	jsr     pusha0
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     (ptr1,x)
	jsr     tossuba0
	sta     _inputWidth
	jmp     L0025
L000C:	lda     _callList
	ora     _callList+1
	beq     L000D
	lda     _callList+1
	sta     ptr1+1
	lda     _callList
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	sta     _txtX
	lda     _callList+1
	sta     ptr1+1
	lda     _callList
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	sta     _txtY
	lda     _callList+1
	sta     ptr1+1
	lda     _callList
	sta     ptr1
	ldy     #$07
	lda     (ptr1),y
	sta     _inkColor
	lda     _callList+1
	sta     ptr1+1
	lda     _callList
	sta     ptr1
	iny
	lda     (ptr1),y
	sta     _paperColor
	lda     _callList
	ldx     _callList+1
	ldy     #$05
	jsr     ldaxidx
	jsr     _PrintStr
L000D:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	sta     _txtX
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	sta     _txtY
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$08
	lda     (ptr1),y
	sta     _inkColor
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	dey
	lda     (ptr1),y
	sta     _paperColor
	lda     M0001
	ldx     M0001+1
	ldy     #$05
	jsr     ldaxidx
	jsr     _PrintStr
	lda     M0001+1
	sta     _callList+1
	lda     M0001
	sta     _callList
	jmp     L0025
L000E:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$07
	lda     (ptr1),y
	sta     _inkColor
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	iny
	lda     (ptr1),y
	sta     _paperColor
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	sta     _txtX
	lda     M0001
	ldx     M0001+1
	jsr     _SliderPos
	sta     _txtY
	lda     #$1D
	jsr     _PrintChr
	lda     M0001
	ldx     M0001+1
	ldy     #$05
	jsr     ldaxidx
	jsr     ldaxi
	sta     M0002
	stx     M0002+1
	lda     M0001
	ldx     M0001+1
	ldy     #$05
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	sta     M0003
	stx     M0003+1
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	ldy     #$00
	cmp     (c_sp),y
	bne     L0024
	lda     M0002
	ora     M0002+1
	jeq     L001B
	lda     M0002
	bne     L0012
	dec     M0002+1
L0012:	dec     M0002
	jmp     L001B
L0024:	lda     (c_sp),y
	jsr     pusha0
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	jsr     decax1
	jsr     tosicmp
	bne     L0014
	lda     M0002
	ldx     M0002+1
	jsr     pushax
	lda     M0003
	ldx     M0003+1
	jsr     decax1
	jsr     tosicmp
	jcs     L001B
	inc     M0002
	jne     L001B
	inc     M0002+1
	jmp     L001B
L0014:	ldx     #$00
	lda     (c_sp,x)
	jsr     pusha0
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	jsr     incax1
	jsr     tosicmp
	bne     L0018
	ldx     #$00
	txa
	jmp     L0026
L0018:	ldx     #$00
	lda     (c_sp,x)
	jsr     pusha0
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	jsr     decax2
	jsr     tosicmp
	bne     L001A
	lda     M0003
	ldx     M0003+1
	jsr     decax1
	jmp     L0026
L001A:	lda     M0003
	ldx     M0003+1
	sta     M0002
	stx     M0002+1
	jsr     pushax
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha0
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	jsr     tossuba0
	jsr     decax1
	jsr     tosumulax
	sta     M0002
	stx     M0002+1
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha0
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	jsr     tossuba0
	jsr     decax2
	jsr     tosudivax
L0026:	sta     M0002
	stx     M0002+1
L001B:	lda     M0001
	ldx     M0001+1
	ldy     #$05
	jsr     ldaxidx
	sta     ptr1
	stx     ptr1+1
	lda     M0002
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     M0002+1
	sta     (ptr1),y
	lda     M0001
	ldx     M0001+1
	jsr     _SliderPos
	sta     _txtY
	lda     #$1F
	jsr     _PrintChr
L0025:	lda     M0004
	sta     _inkColor
	lda     M0005
	sta     _paperColor
	lda     M0001
	ldx     M0001+1
	jmp     incsp2
L0005:	lda     M0001
	ldx     M0001+1
	ldy     #$0B
	jsr     ldaxidx
	sta     M0001
	stx     M0001+1
L0004:	lda     M0001
	ora     M0001+1
	jne     L0002
	tax
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00
M0003:
	.res	2,$00
M0004:
	.res	1,$00
M0005:
	.res	1,$00

.endproc

