;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_free
	.export		_ClearCallbacks
	.import		_callHead
	.import		_callList

; ---------------------------------------------------------------
; void __near__ ClearCallbacks (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ClearCallbacks: near

.segment	"SHADOW_RAM"

	lda     _callHead+1
	sta     M0002+1
	lda     _callHead
	jmp     L0005
L0002:	lda     M0002
	ldx     M0002+1
	ldy     #$0B
	jsr     ldaxidx
	sta     M0001
	stx     M0001+1
	lda     M0002
	ldx     M0002+1
	jsr     _free
	lda     M0001+1
	sta     M0002+1
	lda     M0001
L0005:	sta     M0002
	ora     M0002+1
	bne     L0002
	sta     _callHead
	sta     _callHead+1
	sta     _callList
	sta     _callList+1
	rts

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00

.endproc

