;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_SetChunk
	.import		_ColToX
	.import		_RowToY
	.import		_XToCol
	.import		_YToRow
	.export		_Icon
	.import		_PushCallback

; ---------------------------------------------------------------
; struct $anon-struct-0019 *__near__ Icon (unsigned char col, unsigned char row, unsigned char *chunk)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_Icon: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     pushw0sp
	ldy     #$05
	lda     (c_sp),y
	jsr     _ColToX
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	jsr     _RowToY
	jsr     _SetChunk
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _XToCol
	sta     M0001
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _YToRow
	sta     M0002
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     M0001
	jsr     pusha
	lda     M0002
	jsr     pusha
	lda     #$01
	jsr     _PushCallback
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00

.endproc

