;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_txtY
	.import		_InputStr
	.export		_Input
	.import		_PushCallback

; ---------------------------------------------------------------
; struct $anon-struct-0019 *__near__ Input (unsigned char col, unsigned char row, unsigned char width, unsigned char height, unsigned char *buffer, unsigned char len)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_Input: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$06
	lda     (c_sp),y
	sta     _txtX
	dey
	lda     (c_sp),y
	sta     _txtY
	dey
	lda     (c_sp),y
	jsr     pusha
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     #$01
	jsr     _InputStr
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	lda     #$03
	jsr     _PushCallback
	sta     M0001
	stx     M0001+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	jsr     ldaxysp
	ldy     #$04
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (c_sp),y
	ldy     #$06
	sta     (ptr1),y
	lda     M0001
	ldx     M0001+1
	jmp     incsp7

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

