;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_txtY
	.import		_PrintStr
	.export		_ListBox
	.import		_Panel
	.import		_PushCallback

; ---------------------------------------------------------------
; void __near__ ListBox (unsigned char col, unsigned char row, unsigned char width, unsigned char height, unsigned char *title, unsigned char *labels, unsigned char len)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ListBox: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     #$00
	sta     M0001
	sta     M0002
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	jsr     _Panel
	ldy     #$08
	lda     (c_sp),y
	sta     _txtX
	dey
	lda     (c_sp),y
	clc
	adc     #$01
	sta     _txtY
	jmp     L0012
L0002:	ldy     #$02
	jsr     ldaxysp
	clc
	adc     M0002
	bcc     L0010
	inx
L0010:	sta     M0003
	stx     M0003+1
	jsr     _PrintStr
	lda     _txtX
	jsr     pusha
	lda     _txtY
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$04
	jsr     _PushCallback
	sta     M0004
	stx     M0004+1
	sta     ptr1
	stx     ptr1+1
	lda     M0003
	ldy     #$04
	sta     (ptr1),y
	iny
	lda     M0003+1
	sta     (ptr1),y
	lda     M0004+1
	sta     ptr1+1
	lda     M0004
	sta     ptr1
	lda     M0001
	iny
	sta     (ptr1),y
	jmp     L000B
L0011:	lda     M0002
	cmp     #$FF
	beq     L0003
L000B:	inc     M0002
	lda     M0002
	clc
	ldy     #$01
	adc     (c_sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (c_sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0011
	jmp     L000F
L000C:	lda     M0002
	cmp     #$FF
	beq     L0003
L000F:	inc     M0002
	lda     M0002
	clc
	ldy     #$01
	adc     (c_sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (c_sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	beq     L000C
	inc     _txtY
	inc     M0001
L0012:	lda     M0001
	jsr     pusha0
	ldy     #$07
	lda     (c_sp),y
	jsr     decax1
	jsr     tosicmp
	bpl     L0003
	lda     M0001
	ldy     #$00
	cmp     (c_sp),y
	jcc     L0002
L0003:	ldy     #$09
	jmp     addysp

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	2,$00
M0004:
	.res	2,$00

.endproc

