;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_SetPixel
	.import		_pixelX
	.import		_pixelY
	.import		_txtX
	.import		_txtY
	.import		_inkColor
	.import		_paperColor
	.import		_PrintBlanks
	.import		_PrintStr
	.import		_ColToX
	.import		_RowToY
	.export		_Panel
	.export		_Line

; ---------------------------------------------------------------
; void __near__ Panel (unsigned char col, unsigned char row, unsigned char width, unsigned char height, unsigned char *title)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_Panel: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$05
	lda     (c_sp),y
	sta     _txtX
	dey
	lda     (c_sp),y
	sta     _txtY
	dey
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	jsr     _PrintBlanks
	ldy     #$05
	lda     (c_sp),y
	jsr     _ColToX
	sta     M0001
	ldy     #$03
	lda     (c_sp),y
	clc
	ldy     #$05
	adc     (c_sp),y
	jsr     _ColToX
	sta     M0002
	ldy     #$04
	lda     (c_sp),y
	jsr     _RowToY
	sta     M0003
	ldy     #$02
	lda     (c_sp),y
	clc
	ldy     #$04
	adc     (c_sp),y
	jsr     _RowToY
	sta     M0004
	lda     M0001
	jsr     pusha
	lda     M0002
	jsr     pusha
	lda     M0004
	clc
	adc     #$01
	jsr     pusha
	lda     M0004
	clc
	adc     #$01
	jsr     _Line
	lda     M0001
	sec
	sbc     #$01
	jsr     pusha
	lda     M0001
	sec
	sbc     #$01
	jsr     pusha
	lda     M0003
	jsr     pusha
	lda     M0004
	clc
	adc     #$02
	jsr     _Line
	lda     M0002
	jsr     pusha
	lda     M0002
	jsr     pusha
	lda     M0003
	jsr     pusha
	lda     M0004
	clc
	adc     #$02
	jsr     _Line
	lda     _inkColor
	sta     M0005
	lda     _paperColor
	sta     M0006
	sta     _inkColor
	lda     M0005
	sta     _paperColor
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     #$01
	jsr     _PrintBlanks
	jsr     ldax0sp
	jsr     _PrintStr
	lda     M0005
	sta     _inkColor
	lda     M0006
	sta     _paperColor
	jmp     incsp6

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00
M0004:
	.res	1,$00
M0005:
	.res	1,$00
M0006:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ Line (unsigned char x1, unsigned char x2, unsigned char y1, unsigned char y2)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_Line: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	dey
	cmp     (c_sp),y
	bne     L0002
	iny
	lda     (c_sp),y
	sta     _pixelX
	ldy     #$01
	lda     (c_sp),y
	sta     _pixelY
L000C:	lda     _pixelY
	ldy     #$00
	cmp     (c_sp),y
	bcs     L0009
	lda     _inkColor
	jsr     _SetPixel
	inc     _pixelY
	jmp     L000C
L0002:	dey
	lda     (c_sp),y
	sta     _pixelY
	ldy     #$03
	lda     (c_sp),y
	sta     _pixelX
L000D:	lda     _pixelX
	ldy     #$02
	cmp     (c_sp),y
	bcs     L0009
	lda     _inkColor
	jsr     _SetPixel
	inc     _pixelX
	jmp     L000D
L0009:	jmp     incsp4

.endproc

