;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_free
	.export		_PopCallback
	.import		_callHead

; ---------------------------------------------------------------
; void __near__ PopCallback (struct $anon-struct-0019 *call)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PopCallback: near

.segment	"SHADOW_RAM"

	jsr     pushax
	lda     _callHead+1
	sta     M0002+1
	lda     _callHead
	sta     M0002
	jsr     ldax0sp
	cpx     _callHead+1
	bne     L0006
	cmp     _callHead
	bne     L0006
	jsr     ldax0sp
	ldy     #$0B
	jsr     ldaxidx
	sta     _callHead
	stx     _callHead+1
	jsr     ldax0sp
	jsr     _free
	jmp     incsp2
L0004:	jsr     pushw0sp
	lda     M0002
	ldx     M0002+1
	ldy     #$0B
	jsr     ldaxidx
	jsr     tosicmp
	bne     L0007
	lda     M0002
	ldx     M0002+1
	ldy     #$0B
	jsr     ldaxidx
	sta     M0001
	stx     M0001+1
	lda     M0002+1
	sta     sreg+1
	lda     M0002
	sta     sreg
	lda     M0001
	ldx     M0001+1
	ldy     #$0B
	jsr     ldaxidx
	ldy     #$0A
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
	jsr     ldax0sp
	jsr     _free
	jmp     incsp2
L0007:	lda     M0002
	ldx     M0002+1
	ldy     #$0B
	jsr     ldaxidx
	sta     M0002
	stx     M0002+1
L0006:	lda     M0002
	ora     M0002+1
	bne     L0004
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00

.endproc

