;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_kbhit
	.import		_cgetc
	.import		_txtX
	.import		_txtY
	.import		_inkColor
	.import		_paperColor
	.import		_InputStr
	.export		_ProcessInput
	.export		_inputCall
	.export		_inputWidth

.segment	"BSS"

_inputCall:
	.res	2,$00
_inputWidth:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ ProcessInput (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ProcessInput: near

.segment	"SHADOW_RAM"

	lda     _inputCall
	ora     _inputCall+1
	bne     L0002
	tax
	rts
L0002:	jsr     _kbhit
	tax
	beq     L0005
	lda     _inputCall+1
	sta     ptr1+1
	lda     _inputCall
	sta     ptr1
	ldy     #$07
	lda     (ptr1),y
	sta     _inkColor
	lda     _inputCall+1
	sta     ptr1+1
	lda     _inputCall
	sta     ptr1
	iny
	lda     (ptr1),y
	sta     _paperColor
	lda     _inputCall+1
	sta     ptr1+1
	lda     _inputCall
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	sta     _txtX
	lda     _inputCall+1
	sta     ptr1+1
	lda     _inputCall
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	sta     _txtY
	lda     _inputWidth
	jsr     pusha
	lda     _inputCall
	ldx     _inputCall+1
	ldy     #$05
	jsr     pushwidx
	lda     _inputCall+1
	sta     ptr1+1
	lda     _inputCall
	sta     ptr1
	ldy     #$06
	lda     (ptr1),y
	jsr     pusha
	jsr     _cgetc
	jsr     _InputStr
	tax
	beq     L0005
	ldx     #$00
	txa
	sta     _inputCall
	sta     _inputCall+1
	rts
L0005:	lda     #$01
	rts

.endproc

