;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_malloc
	.import		_inkColor
	.import		_paperColor
	.export		_PushCallback
	.import		_callHead

; ---------------------------------------------------------------
; struct $anon-struct-0019 *__near__ PushCallback (unsigned char col, unsigned char row, unsigned char width, unsigned char height, unsigned char type)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PushCallback: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     _callHead+1
	sta     M0001+1
	lda     _callHead
	sta     M0001
	ldx     #$00
	lda     #$0C
	jsr     _malloc
	sta     M0002
	stx     M0002+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$02
	lda     (c_sp),y
	clc
	ldy     #$04
	adc     (c_sp),y
	ldy     #$01
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$03
	lda     (c_sp),y
	dey
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	dey
	lda     (c_sp),y
	clc
	ldy     #$03
	adc     (c_sp),y
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     _inkColor
	ldy     #$07
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     _paperColor
	iny
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$00
	lda     (c_sp),y
	ldy     #$09
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     #$00
	iny
	sta     (ptr1),y
	iny
	sta     (ptr1),y
	lda     _callHead
	ora     _callHead+1
	bne     L0006
	lda     M0002+1
	sta     _callHead+1
	lda     M0002
	sta     _callHead
	jmp     L0003
L0004:	lda     M0001
	ldx     M0001+1
	ldy     #$0B
	jsr     ldaxidx
	sta     M0001
	stx     M0001+1
L0006:	lda     M0001
	ldx     M0001+1
	ldy     #$0A
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	bne     L0004
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     M0002
	dey
	sta     (ptr1),y
	iny
	lda     M0002+1
	sta     (ptr1),y
L0003:	lda     M0002
	ldx     M0002+1
	jmp     incsp5

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00

.endproc

