;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_txtY
	.import		_PrintChr
	.export		_ScrollBar
	.import		_PushCallback
	.import		_SliderPos

; ---------------------------------------------------------------
; struct $anon-struct-0019 *__near__ ScrollBar (unsigned char col, unsigned char row, unsigned char height, unsigned int *range)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ScrollBar: near

.segment	"SHADOW_RAM"

	jsr     pushax
	lda     #$00
	sta     M0002
	ldy     #$04
	lda     (c_sp),y
	sta     _txtX
	dey
	lda     (c_sp),y
	sta     _txtY
	lda     #$10
	jmp     L0006
L0002:	lda     #$1D
L0006:	jsr     _PrintChr
	inc     _txtY
	lda     _txtY
	jsr     pusha0
	ldy     #$04
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	bcc     L0005
	inx
L0005:	jsr     decax1
	jsr     tosicmp
	bmi     L0002
	lda     #$11
	jsr     _PrintChr
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	jsr     pusha
	lda     #$05
	jsr     _PushCallback
	sta     M0001
	stx     M0001+1
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$04
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	lda     M0001
	ldx     M0001+1
	jsr     _SliderPos
	sta     _txtY
	lda     #$1F
	jsr     _PrintChr
	lda     M0001
	ldx     M0001+1
	jmp     incsp5

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	1,$00

.endproc

