;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_SliderPos
	.export		_fraction

.segment	"BSS"

_fraction:
	.res	4,$00

; ---------------------------------------------------------------
; unsigned char __near__ SliderPos (struct $anon-struct-0019 *call)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SliderPos: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     ldax0sp
	ldy     #$05
	jsr     ldaxidx
	jsr     ldaxi
	jsr     axulong
	sta     _fraction
	stx     _fraction+1
	ldy     sreg
	sty     _fraction+2
	ldy     sreg+1
	sty     _fraction+3
	lda     _fraction+3
	sta     sreg+1
	lda     _fraction+2
	sta     sreg
	ldx     _fraction+1
	lda     _fraction
	jsr     pusheax
	ldy     #$05
	jsr     ldptr1ysp
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$07
	jsr     ldptr1ysp
	ldy     #$02
	lda     (ptr1),y
	jsr     tossuba0
	jsr     decax2
	jsr     axlong
	jsr     tosumuleax
	sta     _fraction
	stx     _fraction+1
	ldy     sreg
	sty     _fraction+2
	ldy     sreg+1
	sty     _fraction+3
	lda     _fraction+3
	sta     sreg+1
	lda     _fraction+2
	sta     sreg
	ldx     _fraction+1
	lda     _fraction
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     axulong
	jsr     tosudiveax
	sta     _fraction
	stx     _fraction+1
	ldy     sreg
	sty     _fraction+2
	ldy     sreg+1
	sty     _fraction+3
	jsr     ldptr10sp
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha0
	lda     _fraction+3
	sta     sreg+1
	lda     _fraction+2
	sta     sreg
	ldx     _fraction+1
	lda     _fraction
	jsr     tosulong
	jsr     tosaddeax
	ldy     #$01
	jsr     inceaxy
	ldx     #$00
	jmp     incsp2

.endproc

