;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memset
	.import		_doubleBuffer
	.import		_txtX
	.import		_txtY
	.import		_paperColor
	.export		_PrintBlanks
	.import		_paperColor1
	.import		_paperColor2
	.import		_bgByte1
	.import		_bgByte2

; ---------------------------------------------------------------
; void __near__ PrintBlanks (unsigned char width, unsigned char height)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PrintBlanks: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     #$00
	sta     M0001
	lda     _paperColor
	and     #$03
	sta     _paperColor1
	lda     _paperColor
	lsr     a
	lsr     a
	sta     _paperColor2
	lda     _txtY
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	pha
	lda     #$A0
	adc     ptr1+1
	tax
	pla
	clc
	adc     _txtX
	bcc     L000B
	inx
L000B:	sta     M0002
	stx     M0002+1
	lda     _txtY
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	pha
	lda     #$70
	adc     ptr1+1
	tax
	pla
	clc
	adc     _txtX
	bcc     L000C
	inx
L000C:	sta     M0003
	stx     M0003+1
	lda     _paperColor1
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     _paperColor2
	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor1
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor2
	ora     ptr1
	sta     _bgByte1
	lda     _paperColor2
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     _paperColor1
	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor2
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor1
	ora     ptr1
	sta     _bgByte2
	jmp     L000E
L0002:	lda     M0001
	and     #$01
	beq     L0005
	lda     M0002
	ldx     M0002+1
	jsr     pushax
	lda     _bgByte2
	jsr     pusha0
	ldy     #$05
	lda     (c_sp),y
	jsr     _memset
	lda     _doubleBuffer
	beq     L0008
	lda     M0003
	ldx     M0003+1
	jsr     pushax
	lda     _bgByte1
	jmp     L0011
L0005:	lda     M0002
	ldx     M0002+1
	jsr     pushax
	lda     _bgByte1
	jsr     pusha0
	ldy     #$05
	lda     (c_sp),y
	jsr     _memset
	lda     _doubleBuffer
	beq     L0008
	lda     M0003
	ldx     M0003+1
	jsr     pushax
	lda     _bgByte2
L0011:	jsr     pusha0
	ldy     #$05
	lda     (c_sp),y
	jsr     _memset
L0008:	lda     #$28
	clc
	adc     M0002
	sta     M0002
	bcc     L0009
	inc     M0002+1
L0009:	lda     #$28
	clc
	adc     M0003
	sta     M0003
	bcc     L000A
	inc     M0003+1
L000A:	inc     M0001
L000E:	lda     M0001
	jsr     pusha0
	ldy     #$02
	lda     (c_sp),y
	jsr     shlax3
	jsr     tosicmp
	jmi     L0002
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	2,$00
M0003:
	.res	2,$00

.endproc

