;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.export		_CopyStr

; ---------------------------------------------------------------
; void __near__ CopyStr (unsigned char col1, unsigned char row1, unsigned char col2, unsigned char row2, unsigned char len)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_CopyStr: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0008
	inx
L0008:	sta     M0002
	stx     M0002+1
	iny
	lda     (c_sp),y
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0009
	inx
L0009:	sta     M0003
	stx     M0003+1
	lda     #$00
	sta     M0001
L000A:	lda     M0001
	cmp     #$08
	bcs     L0003
	lda     #$10
	clc
	adc     M0003
	pha
	lda     #$A0
	adc     M0003+1
	tax
	pla
	jsr     pushax
	lda     #$10
	clc
	adc     M0002
	pha
	lda     #$A0
	adc     M0002+1
	tax
	pla
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     _memcpy
	lda     #$10
	clc
	adc     M0003
	pha
	lda     #$70
	adc     M0003+1
	tax
	pla
	jsr     pushax
	lda     #$10
	clc
	adc     M0002
	pha
	lda     #$70
	adc     M0002+1
	tax
	pla
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     _memcpy
	lda     #$28
	clc
	adc     M0002
	sta     M0002
	bcc     L0006
	inc     M0002+1
L0006:	lda     #$28
	clc
	adc     M0003
	sta     M0003
	bcc     L0007
	inc     M0003+1
L0007:	inc     M0001
	jmp     L000A
L0003:	jmp     incsp5

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	2,$00
M0003:
	.res	2,$00

.endproc

