;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_txtY
	.export		_BackupCursor
	.export		_RestoreCursor
	.export		_bckX
	.export		_bckY

.segment	"BSS"

_bckX:
	.res	1,$00
_bckY:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ BackupCursor (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_BackupCursor: near

.segment	"SHADOW_RAM"

	lda     _txtX
	sta     _bckX
	lda     _txtY
	sta     _bckY
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ RestoreCursor (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_RestoreCursor: near

.segment	"SHADOW_RAM"

	lda     _bckX
	sta     _txtX
	lda     _bckY
	sta     _txtY
	rts

.endproc

