;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_ClearBitmap
	.import		_txtX
	.import		_txtY
	.import		_inkColor
	.import		_paperColor
	.import		_PrintNum
	.import		_PrintStr
	.export		_GuruMeditation

.segment	"RODATA"

S0002:
	.byte	$62,$20,$6F,$76,$65,$72,$66,$6C,$6F,$77,$20,$69,$6E,$00

; ---------------------------------------------------------------
; void __near__ GuruMeditation (unsigned char *souce, unsigned int overflow)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_GuruMeditation: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     _ClearBitmap
	lda     #$00
	sta     _paperColor
	lda     #$05
	sta     _inkColor
	lda     #$0C
	sta     _txtY
	lda     #$07
	sta     _txtX
	jsr     ldax0sp
	jsr     _PrintNum
	lda     #$0B
	sta     _txtX
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _PrintStr
	lda     #$1A
	sta     _txtX
	ldy     #$03
	jsr     ldaxysp
	jsr     _PrintStr
L0005:	jmp     L0005

.endproc

