;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_strlen
	.import		_txtX
	.import		_txtY
	.import		_PrintBlanks
	.import		_PrintChr
	.import		_CopyStr
	.export		_InputStr
	.export		_maskInput

.segment	"DATA"

_maskInput:
	.byte	$00

; ---------------------------------------------------------------
; unsigned char __near__ InputStr (unsigned char width, char *buffer, unsigned char len, unsigned char key)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_InputStr: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     _txtX
	sta     M0004
	lda     #$2A
	sta     M0005
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	sta     M0002
	ldy     #$04
	cmp     (c_sp),y
	bcs     L0026
	lda     M0002
	jmp     L0023
L0026:	lda     (c_sp),y
L0023:	sta     M0003
	ldy     #$00
	lda     (c_sp),y
	cmp     #$02
	bcs     L002A
	ldy     #$04
	lda     (c_sp),y
	clc
	adc     #$01
	jsr     pusha
	lda     #$01
	jsr     _PrintBlanks
	lda     M0002
	sec
	sbc     M0003
	sta     M0001
	jmp     L0028
L0005:	lda     _maskInput
	bne     L0027
	ldy     #$03
	jsr     ldaxysp
	ldy     M0001
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0005
L0027:	lda     M0005
	jsr     _PrintChr
	inc     _txtX
	inc     M0001
L0028:	lda     M0001
	cmp     M0002
	bcc     L0005
	jmp     L0017
L002A:	lda     (c_sp),y
	cmp     #$9B
	bne     L002C
	lda     M0003
	clc
	adc     _txtX
	sta     _txtX
	lda     #$20
	jsr     _PrintChr
	lda     M0003
	eor     #$FF
	sec
	adc     _txtX
	sta     _txtX
	ldx     #$00
	lda     #$01
	jmp     incsp5
L002C:	lda     (c_sp),y
	cmp     #$7E
	jne     L0030
	lda     M0002
	jeq     L0032
	ldx     #$00
	lda     M0002
	jsr     decax1
	clc
	ldy     #$02
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     M0002
	ldy     #$04
	cmp     (c_sp),y
	bcc     L002F
	beq     L002F
	lda     (c_sp),y
	sec
	sbc     #$01
	sta     M0001
L002D:	lda     M0001
	beq     L0010
	lda     _txtX
	clc
	adc     M0001
	jsr     pusha
	lda     _txtY
	jsr     pusha
	lda     _txtX
	clc
	adc     M0001
	sec
	sbc     #$01
	jsr     pusha
	lda     _txtY
	jsr     pusha
	lda     #$01
	jsr     _CopyStr
	dec     M0001
	jmp     L002D
L0010:	lda     _maskInput
	bne     L002E
	lda     M0002
	sec
	ldy     #$04
	sbc     (c_sp),y
	ldx     #$00
	bcs     L0022
	dex
L0022:	jsr     decax1
	clc
	ldy     #$02
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     M0005
L002E:	lda     M0005
	jsr     _PrintChr
	lda     M0003
	clc
	adc     _txtX
	sta     _txtX
	jmp     L0016
L002F:	lda     M0003
	clc
	adc     _txtX
	sta     _txtX
	lda     #$20
	jsr     _PrintChr
	dec     _txtX
	jmp     L0016
L0030:	lda     M0002
	iny
	cmp     (c_sp),y
	jcs     L003A
L0016:	ldy     #$00
L0032:	lda     (c_sp),y
	cmp     #$20
	bcc     L0038
	cmp     #$7B
	bcs     L0038
	ldy     #$03
	jsr     ldptr1ysp
	ldy     #$00
	lda     (c_sp),y
	ldy     M0002
	sta     (ptr1),y
	ldx     #$00
	lda     M0002
	jsr     incax1
	clc
	ldy     #$02
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     M0002
	ldy     #$04
	cmp     (c_sp),y
	bcc     L001B
	lda     _txtX
	jsr     pusha
	lda     _txtY
	jsr     pusha
	lda     _txtX
	clc
	adc     #$01
	jsr     pusha
	lda     _txtY
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	sec
	sbc     #$01
	jsr     _CopyStr
	dec     M0003
L001B:	lda     _maskInput
	bne     L0036
	tay
	lda     (c_sp),y
	sta     M0005
L0036:	lda     M0003
	clc
	adc     _txtX
	sta     _txtX
	lda     M0005
	jsr     _PrintChr
	inc     _txtX
L0017:	ldy     #$00
L0038:	lda     (c_sp),y
	cmp     #$01
	beq     L0039
	lda     #$5F
	jsr     _PrintChr
L0039:	lda     M0004
	sta     _txtX
L003A:	ldx     #$00
	txa
	jmp     incsp5

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00
M0004:
	.res	1,$00
M0005:
	.res	1,$00

.endproc

