;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_PrintChr
	.export		_PrintNum

; ---------------------------------------------------------------
; void __near__ PrintNum (unsigned int num)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PrintNum: near

.segment	"SHADOW_RAM"

	jsr     pushax
	lda     _txtX
	sta     M0002
	ldx     #$00
	lda     #$01
	jmp     L000E
L0002:	lda     M0003
	ldx     M0003+1
	jsr     mulax10
L000E:	sta     M0003
	stx     M0003+1
	lda     M0003
	ldx     M0003+1
	jsr     mulax10
	sec
	ldy     #$00
	sbc     (c_sp),y
	sta     tmp1
	txa
	iny
	sbc     (c_sp),y
	ora     tmp1
	bcc     L0002
	beq     L0002
	jmp     L0007
L0005:	jsr     ldax0sp
	cmp     M0003
	txa
	sbc     M0003+1
	lda     #$00
	bcc     L000D
	jsr     pushw0sp
	lda     M0003
	ldx     M0003+1
	jsr     tosudivax
	sta     M0001
	lda     M0001
	jsr     pusha0
	lda     M0003
	ldx     M0003+1
	jsr     tosumulax
	jsr     subeq0sp
	jmp     L000A
L000D:	sta     M0001
L000A:	ldx     #$00
	lda     M0001
	ldy     #$30
	jsr     incaxy
	jsr     _PrintChr
	inc     _txtX
	lda     M0003
	ldx     M0003+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     M0003
	stx     M0003+1
L0007:	lda     M0003
	ora     M0003+1
	bne     L0005
	lda     M0002
	sta     _txtX
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	2,$00

.endproc

