;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_doubleBuffer
	.import		_charData
	.export		_txtX
	.export		_txtY
	.export		_inkColor
	.export		_paperColor
	.export		_PrintChr
	.export		_PrintStr
	.export		_inkColor1
	.export		_inkColor2
	.export		_paperColor1
	.export		_paperColor2
	.export		_bgByte1
	.export		_bgByte2

.segment	"DATA"

_inkColor:
	.byte	$0B
_paperColor:
	.byte	$00

.segment	"BSS"

_txtX:
	.res	1,$00
_txtY:
	.res	1,$00
_inkColor1:
	.res	1,$00
_inkColor2:
	.res	1,$00
_paperColor1:
	.res	1,$00
_paperColor2:
	.res	1,$00
_bgByte1:
	.res	1,$00
_bgByte2:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ PrintChr (char chr)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PrintChr: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	cmp     #$61
	ldx     #$00
	bcc     L0038
	lda     (c_sp),y
	sec
	sbc     #$20
	sta     (c_sp),y
L0038:	lda     (c_sp),y
	jsr     decax8
	jsr     mulax3
	clc
	adc     #<(_charData)
	sta     M0001
	txa
	adc     #>(_charData)
	sta     M0001+1
	lda     _inkColor
	and     #$03
	sta     _inkColor1
	lda     _inkColor
	lsr     a
	lsr     a
	sta     _inkColor2
	lda     _paperColor
	and     #$03
	sta     _paperColor1
	lda     _paperColor
	lsr     a
	lsr     a
	sta     _paperColor2
	lda     _paperColor1
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     _paperColor2
	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor1
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor2
	ora     ptr1
	sta     _bgByte1
	lda     _paperColor2
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     _paperColor1
	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor2
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor1
	ora     ptr1
	sta     _bgByte2
	lda     _txtY
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	clc
	adc     _txtX
	bcc     L0034
	inx
L0034:	sta     M0005
	stx     M0005+1
	sta     M0004
	stx     M0004+1
	lda     #$10
	clc
	adc     M0004
	sta     M0004
	lda     #$A0
	adc     M0004+1
	sta     M0004+1
	lda     #$10
	clc
	adc     M0005
	sta     M0005
	lda     #$70
	adc     M0005+1
	sta     M0005+1
	ldy     #$00
	lda     (c_sp),y
	cmp     #$20
	bne     L0003
	sty     M0002
L0039:	lda     M0002
	cmp     #$08
	jcs     L0033
	and     #$01
	beq     L0008
	lda     M0004+1
	sta     ptr1+1
	lda     M0004
	sta     ptr1
	lda     _bgByte2
	sta     (ptr1),y
	lda     _doubleBuffer
	beq     L000B
	lda     M0005+1
	sta     ptr1+1
	lda     M0005
	sta     ptr1
	lda     _bgByte1
	jmp     L0036
L0008:	lda     M0004+1
	sta     ptr1+1
	lda     M0004
	sta     ptr1
	lda     _bgByte1
	sta     (ptr1),y
	lda     _doubleBuffer
	beq     L000B
	lda     M0005+1
	sta     ptr1+1
	lda     M0005
	sta     ptr1
	lda     _bgByte2
L0036:	sta     (ptr1),y
L000B:	lda     #$28
	clc
	adc     M0004
	sta     M0004
	bcc     L000C
	inc     M0004+1
L000C:	lda     #$28
	clc
	adc     M0005
	sta     M0005
	bcc     L000D
	inc     M0005+1
L000D:	inc     M0002
	jmp     L0039
L0003:	lda     M0004+1
	sta     ptr1+1
	lda     M0004
	sta     ptr1
	lda     _bgByte1
	sta     (ptr1),y
	lda     #$28
	clc
	adc     M0004
	sta     M0004
	bcc     L000F
	inc     M0004+1
L000F:	lda     _doubleBuffer
	beq     L0010
	lda     M0005+1
	sta     ptr1+1
	lda     M0005
	sta     ptr1
	lda     _bgByte2
	sta     (ptr1),y
L0010:	lda     #$28
	clc
	adc     M0005
	sta     M0005
	bcc     L0011
	inc     M0005+1
L0011:	sty     M0002
L003A:	lda     M0002
	cmp     #$03
	jcs     L0013
	lda     M0001
	ldx     M0001+1
	ldy     M0002
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0003
	lda     M0004+1
	sta     sreg+1
	lda     M0004
	sta     sreg
	lda     M0003
	and     #$80
	beq     L003B
	lda     _inkColor2
	jmp     L0017
L003B:	lda     _paperColor2
L0017:	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     M0003
	and     #$40
	beq     L003C
	lda     _inkColor1
	jmp     L0019
L003C:	lda     _paperColor1
L0019:	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     M0003
	and     #$20
	beq     L003D
	lda     _inkColor2
	jmp     L001B
L003D:	lda     _paperColor2
L001B:	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor1
	ora     ptr1
	ldy     #$00
	sta     (sreg),y
	lda     #$28
	clc
	adc     M0004
	sta     M0004
	bcc     L001C
	inc     M0004+1
L001C:	lda     M0004+1
	sta     sreg+1
	lda     M0004
	sta     sreg
	lda     M0003
	and     #$08
	beq     L003E
	lda     _inkColor1
	jmp     L001E
L003E:	lda     _paperColor1
L001E:	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     M0003
	and     #$04
	beq     L003F
	lda     _inkColor2
	jmp     L0020
L003F:	lda     _paperColor2
L0020:	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     M0003
	and     #$02
	beq     L0040
	lda     _inkColor1
	jmp     L0022
L0040:	lda     _paperColor1
L0022:	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor2
	ora     ptr1
	sta     (sreg),y
	lda     #$28
	clc
	adc     M0004
	sta     M0004
	bcc     L0023
	inc     M0004+1
L0023:	lda     _doubleBuffer
	jeq     L0014
	lda     M0005+1
	sta     sreg+1
	lda     M0005
	sta     sreg
	lda     M0003
	and     #$80
	beq     L0041
	lda     _inkColor1
	jmp     L0026
L0041:	lda     _paperColor1
L0026:	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     M0003
	and     #$40
	beq     L0042
	lda     _inkColor2
	jmp     L0028
L0042:	lda     _paperColor2
L0028:	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     M0003
	and     #$20
	beq     L0043
	lda     _inkColor1
	jmp     L002A
L0043:	lda     _paperColor1
L002A:	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor2
	ora     ptr1
	sta     (sreg),y
	lda     #$28
	clc
	adc     M0005
	sta     M0005
	bcc     L002B
	inc     M0005+1
L002B:	lda     M0005+1
	sta     sreg+1
	lda     M0005
	sta     sreg
	lda     M0003
	and     #$08
	beq     L0044
	lda     _inkColor2
	jmp     L002D
L0044:	lda     _paperColor2
L002D:	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     M0003
	and     #$04
	beq     L0045
	lda     _inkColor1
	jmp     L002F
L0045:	lda     _paperColor1
L002F:	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     M0003
	and     #$02
	beq     L0046
	lda     _inkColor2
	jmp     L0031
L0046:	lda     _paperColor2
L0031:	asl     a
	asl     a
	ora     ptr1
	sta     ptr1
	lda     _paperColor1
	ora     ptr1
	sta     (sreg),y
	lda     #$28
	clc
	adc     M0005
	sta     M0005
	bcc     L0014
	inc     M0005+1
L0014:	inc     M0002
	jmp     L003A
L0013:	lda     M0004+1
	sta     ptr1+1
	lda     M0004
	sta     ptr1
	lda     _bgByte2
	sta     (ptr1),y
	lda     _doubleBuffer
	beq     L0033
	lda     M0005+1
	sta     ptr1+1
	lda     M0005
	sta     ptr1
	lda     _bgByte1
	sta     (ptr1),y
L0033:	jmp     incsp1

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00
M0004:
	.res	2,$00
M0005:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; void __near__ PrintStr (const char *buffer)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PrintStr: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     ldax0sp
	sta     M0001
	stx     M0001+1
	lda     _txtX
	sta     M0002
	jmp     L0004
L0002:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	jsr     _PrintChr
	inc     M0001
	bne     L0005
	inc     M0001+1
L0005:	inc     _txtX
L0004:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	bne     L0002
	lda     M0002
	sta     _txtX
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	1,$00

.endproc

