;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_txtX
	.import		_txtY
	.export		_PrintLogo
	.export		_logos

.segment	"RODATA"

_logos:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$20
	.byte	$88
	.byte	$80
	.byte	$84
	.byte	$20
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$10
	.byte	$30
	.byte	$FC
	.byte	$A8
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0C
	.byte	$30
	.byte	$54
	.byte	$A8
	.byte	$20
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$34
	.byte	$DC
	.byte	$DC
	.byte	$70
	.byte	$54
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$50
	.byte	$10
	.byte	$34
	.byte	$4C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$44
	.byte	$54
	.byte	$54
	.byte	$54
	.byte	$44
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$BC
	.byte	$BE
	.byte	$AA
	.byte	$BE
	.byte	$AA

; ---------------------------------------------------------------
; void __near__ PrintLogo (unsigned char index)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PrintLogo: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	cmp     #$07
	bcc     L000D
	lda     #$06
	sta     (c_sp),y
L000D:	lda     _txtY
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	pha
	lda     #$A0
	adc     ptr1+1
	tax
	pla
	clc
	adc     _txtX
	bcc     L0009
	inx
L0009:	sta     M0001
	stx     M0001+1
	lda     _txtY
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	pha
	lda     #$70
	adc     ptr1+1
	tax
	pla
	clc
	adc     _txtX
	bcc     L000A
	inx
L000A:	sta     M0002
	stx     M0002+1
	lda     #$00
	sta     M0003
L000E:	lda     M0003
	cmp     #$08
	bcs     L0004
	lda     M0001+1
	sta     sreg+1
	lda     M0001
	sta     sreg
	ldx     #$00
	lda     (c_sp,x)
	jsr     aslax3
	clc
	adc     #<(_logos)
	sta     ptr1
	txa
	adc     #>(_logos)
	sta     ptr1+1
	ldy     M0003
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	lda     #$28
	clc
	adc     M0001
	sta     M0001
	bcc     L0007
	inc     M0001+1
L0007:	lda     M0002+1
	sta     sreg+1
	lda     M0002
	sta     sreg
	ldx     #$00
	lda     (c_sp),y
	jsr     aslax3
	clc
	adc     #<(_logos)
	sta     ptr1
	txa
	adc     #>(_logos)
	sta     ptr1+1
	ldy     M0003
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	lda     #$28
	clc
	adc     M0002
	sta     M0002
	bcc     L0008
	inc     M0002+1
L0008:	inc     M0003
	jmp     L000E
L0004:	jmp     incsp1

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00
M0003:
	.res	1,$00

.endproc

