;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_kbhit
	.import		_cgetc
	.import		_clock
	.import		_txtX
	.import		_txtY
	.import		_inkColor
	.import		_PrintBlanks
	.import		_PrintChr
	.import		_PrintStr
	.import		_GetJoy
	.export		_cursorLocked
	.export		_cursorMoved
	.export		_cursorCol
	.export		_cursorRow
	.export		_cursorHeight
	.export		_cursorPos
	.export		_cursorActions
	.export		_InitMenu
	.export		_UpdateMenu
	.export		_cursorClock
	.export		_cursorFlick

.segment	"BSS"

_cursorLocked:
	.res	1,$00
_cursorMoved:
	.res	1,$00
_cursorCol:
	.res	1,$00
_cursorRow:
	.res	1,$00
_cursorHeight:
	.res	1,$00
_cursorPos:
	.res	1,$00
_cursorActions:
	.res	2,$00
_cursorClock:
	.res	4,$00
_cursorFlick:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ InitMenu (unsigned char col, unsigned char row, unsigned char width, unsigned char height, unsigned char padding, unsigned char **labels, unsigned char *actions)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_InitMenu: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$08
	lda     (c_sp),y
	sta     _cursorCol
	dey
	lda     (c_sp),y
	sta     _cursorPos
	sta     _cursorRow
	ldy     #$05
	lda     (c_sp),y
	sta     _cursorHeight
	jsr     ldax0sp
	sta     _cursorActions
	stx     _cursorActions+1
	ldy     #$08
	lda     (c_sp),y
	sec
	ldy     #$04
	sbc     (c_sp),y
	sta     _txtX
	ldy     #$07
	lda     (c_sp),y
	sec
	ldy     #$04
	sbc     (c_sp),y
	sta     _txtY
	lda     (c_sp),y
	asl     a
	bcc     L000B
	clc
L000B:	ldy     #$06
	adc     (c_sp),y
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	asl     a
	bcc     L000C
	clc
L000C:	iny
	adc     (c_sp),y
	jsr     _PrintBlanks
	ldy     #$08
	lda     (c_sp),y
	clc
	adc     #$02
	sta     _txtX
	lda     _cursorRow
	sta     _txtY
	lda     #$00
	sta     M0001
L000E:	lda     M0001
	ldy     #$05
	cmp     (c_sp),y
	bcs     L0003
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L000D
	inx
	clc
L000D:	ldy     #$02
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     ldaxi
	jsr     _PrintStr
	inc     _txtY
	inc     M0001
	jmp     L000E
L0003:	ldy     #$09
	jmp     addysp

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ UpdateMenu (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_UpdateMenu: near

.segment	"SHADOW_RAM"

	lda     #$00
	sta     _cursorMoved
	jsr     _kbhit
	tax
	beq     L0002
	jmp     _cgetc
L0002:	jsr     _clock
	jsr     pusheax
	lda     _cursorClock+3
	sta     sreg+1
	lda     _cursorClock+2
	sta     sreg
	ldx     _cursorClock+1
	lda     _cursorClock
	jsr     tossubeax
	cmp     #$15
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	lda     #$00
	bcc     L0012
	jsr     _clock
	sta     _cursorClock
	stx     _cursorClock+1
	ldy     sreg
	sty     _cursorClock+2
	ldy     sreg+1
	sty     _cursorClock+3
	lda     _cursorCol
	sta     _txtX
	lda     _cursorRow
	sta     _txtY
	lda     #$02
	jsr     pusha
	lda     _cursorHeight
	jsr     _PrintBlanks
	lda     _cursorFlick
	beq     L0004
	lda     #$0F
	sta     _inkColor
	lda     _cursorPos
	sta     _txtY
	lda     _cursorCol
	sta     _txtX
	lda     #$2D
	jsr     _PrintChr
	inc     _txtX
	lda     #$3E
	jsr     _PrintChr
	lda     #$0B
	sta     _inkColor
L0004:	lda     _cursorFlick
	jsr     bnega
	sta     _cursorFlick
	lda     #$00
L0012:	jsr     _GetJoy
	sta     M0001
	eor     #$FF
	and     #$1F
	beq     L0015
	lda     _cursorLocked
	beq     L0013
	ldx     #$00
	jmp     L0010
L0013:	lda     #$01
	sta     _cursorLocked
	sta     _cursorFlick
	lda     #$00
	sta     _cursorClock+3
	sta     _cursorClock+2
	sta     _cursorClock+1
	sta     _cursorClock
	jmp     L0016
L0015:	sta     _cursorLocked
L0016:	lda     M0001
	and     #$01
	bne     L0017
	dec     _cursorPos
	lda     #$01
	sta     _cursorMoved
L0017:	lda     M0001
	and     #$02
	bne     L0018
	inc     _cursorPos
	lda     #$01
	sta     _cursorMoved
L0018:	lda     _cursorPos
	cmp     _cursorRow
	bcs     L0019
	lda     _cursorRow
	clc
	adc     _cursorHeight
	sec
	sbc     #$01
	sta     _cursorPos
L0019:	lda     _cursorPos
	jsr     pusha0
	lda     _cursorRow
	clc
	adc     _cursorHeight
	bcc     L000E
	ldx     #$01
L000E:	jsr     tosicmp
	bmi     L000B
	lda     _cursorRow
	sta     _cursorPos
L000B:	lda     M0001
	ldx     #$00
	and     #$10
	bne     L0010
	lda     _cursorPos
	sec
	sbc     _cursorRow
	bcs     L000F
	dex
L000F:	clc
	adc     _cursorActions
	sta     ptr1
	txa
	adc     _cursorActions+1
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	rts
L0010:	txa
	rts

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

