;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_ParallaxDLIST
	.import		_SetPalette
	.import		_chrPalette
	.import		_screenWidth
	.import		_blockWidth
	.import		_lineWidth
	.import		_screenData
	.import		_InitBitmap
	.import		_parallaxDLI
	.export		_InitParallax
	.export		_ShowParallax
	.export		_HideParallax

; ---------------------------------------------------------------
; void __near__ InitParallax (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_InitParallax: near

.segment	"SHADOW_RAM"

	lda     #$2C
	sta     _lineWidth
	sta     _blockWidth
	sta     _screenWidth
	ldx     #$09
	lda     #$70
	sta     _screenData
	stx     _screenData+1
	jmp     _InitBitmap

.endproc

; ---------------------------------------------------------------
; void __near__ ShowParallax (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ShowParallax: near

.segment	"SHADOW_RAM"

	jsr     _ParallaxDLIST
	lda     #$01
	sta     _parallaxDLI
	lda     $022F
	ora     #$20
	sta     $022F
	lda     #<(_chrPalette)
	ldx     #>(_chrPalette)
	jmp     _SetPalette

.endproc

; ---------------------------------------------------------------
; void __near__ HideParallax (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_HideParallax: near

.segment	"SHADOW_RAM"

	lda     $022F
	and     #$DF
	sta     $022F
	lda     #$00
	sta     _parallaxDLI
	rts

.endproc

