;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_GetPixel
	.export		_SetPixel
	.export		_LocatePixel
	.export		_pixelX
	.export		_pixelY

.segment	"BSS"

_pixelX:
	.res	1,$00
_pixelY:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ GetPixel (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_GetPixel: near

.segment	"SHADOW_RAM"

	lda     _pixelY
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	sta     ptr1
	stx     ptr1+1
	lda     _pixelX
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0007
	inx
L0007:	sta     M0001
	stx     M0001+1
	lda     #$06
	jsr     pusha0
	lda     _pixelX
	and     #$03
	asl     a
	bcc     L0006
	ldx     #$01
L0006:	jsr     tossubax
	sta     M0002
	tay
	lda     #$03
	ldx     #$00
	jsr     aslaxy
	sta     M0003
	lda     #$10
	clc
	adc     M0001
	sta     ptr1
	lda     #$A0
	adc     M0001+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ldx     #$00
	and     M0003
	sta     ptr1
	ldy     M0002
	lda     ptr1
	jsr     asraxy
	sta     M0004
	lda     #$10
	clc
	adc     M0001
	sta     ptr1
	lda     #$70
	adc     M0001+1
	sta     ptr1+1
	lda     (ptr1,x)
	and     M0003
	sta     ptr1
	ldy     M0002
	lda     ptr1
	jsr     asraxy
	sta     M0005
	lda     M0004
	cmp     M0005
	bcc     L0009
	beq     L0009
	asl     a
	asl     a
	clc
	adc     M0005
	rts
L0009:	lda     M0005
	asl     a
	asl     a
	clc
	adc     M0004
	rts

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00
M0004:
	.res	1,$00
M0005:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ SetPixel (unsigned char color)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SetPixel: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     _pixelY
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	sta     ptr1
	stx     ptr1+1
	lda     _pixelX
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0006
	inx
L0006:	sta     M0001
	stx     M0001+1
	lda     #$06
	jsr     pusha0
	lda     _pixelX
	and     #$03
	asl     a
	bcc     L0005
	ldx     #$01
L0005:	jsr     tossubax
	sta     M0002
	tay
	lda     #$03
	ldx     #$00
	jsr     aslaxy
	eor     #$FF
	sta     M0003
	lda     _pixelY
	clc
	adc     _pixelX
	and     #$01
	beq     L0002
	ldy     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$03
	sta     ptr1
	ldy     M0002
	lda     ptr1
	jsr     aslaxy
	sta     M0005
	ldx     #$00
	lda     (c_sp,x)
	lsr     a
	lsr     a
	sta     ptr1
	ldy     M0002
	lda     ptr1
	jsr     aslaxy
	sta     M0004
	jmp     L0003
L0002:	tay
	lda     (c_sp),y
	ldx     #$00
	and     #$03
	sta     ptr1
	ldy     M0002
	lda     ptr1
	jsr     aslaxy
	sta     M0004
	ldx     #$00
	lda     (c_sp,x)
	lsr     a
	lsr     a
	sta     ptr1
	ldy     M0002
	lda     ptr1
	jsr     aslaxy
	sta     M0005
L0003:	lda     #$10
	clc
	adc     M0001
	sta     sreg
	lda     #$A0
	adc     M0001+1
	sta     sreg+1
	lda     #$10
	clc
	adc     M0001
	sta     ptr1
	lda     #$A0
	adc     M0001+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	and     M0003
	sta     ptr1
	lda     M0004
	ora     ptr1
	sta     (sreg),y
	lda     #$10
	clc
	adc     M0001
	sta     sreg
	lda     #$70
	adc     M0001+1
	sta     sreg+1
	lda     #$10
	clc
	adc     M0001
	sta     ptr1
	lda     #$70
	adc     M0001+1
	sta     ptr1+1
	lda     (ptr1),y
	and     M0003
	sta     ptr1
	lda     M0005
	ora     ptr1
	sta     (sreg),y
	jmp     incsp1

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00
M0004:
	.res	1,$00
M0005:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ LocatePixel (unsigned int x, unsigned int y)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LocatePixel: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     shrax1
	sta     _pixelX
	ldy     #$00
	lda     (c_sp),y
	sta     _pixelY
	jmp     incsp4

.endproc

