;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_ColToX
	.export		_RowToY
	.export		_XToCol
	.export		_YToRow

; ---------------------------------------------------------------
; unsigned char __near__ ColToX (unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ColToX: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	asl     a
	asl     a
	ldx     #$00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ RowToY (unsigned char row)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RowToY: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	asl     a
	asl     a
	asl     a
	ldx     #$00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ XToCol (unsigned char x)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_XToCol: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	lsr     a
	lsr     a
	ldx     #$00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ YToRow (unsigned char y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_YToRow: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	lsr     a
	lsr     a
	lsr     a
	ldx     #$00
	jmp     incsp1

.endproc

