;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_InitJoy
	.export		_GetJoy
	.export		_joyAdaptor

.segment	"DATA"

_joyAdaptor:
	.byte	$00

; ---------------------------------------------------------------
; void __near__ InitJoy (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_InitJoy: near

.segment	"SHADOW_RAM"

	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ GetJoy (unsigned char joy)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_GetJoy: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldx     #$02
	lda     #$84
	ldy     #$00
	clc
	adc     (c_sp),y
	bcc     L0002
	inx
L0002:	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     aslax4
	sta     sreg
	stx     sreg+1
	ldx     #$02
	lda     #$78
	clc
	adc     (c_sp),y
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	clc
	adc     sreg
	ldx     sreg+1
	bcc     L0004
	inx
L0004:	ldy     #$20
	jsr     incaxy
	ldx     #$00
	jmp     incsp1

.endproc

