;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_clock
	.import		_GetJoy
	.export		_GetMouse
	.export		_mouseState
	.export		_mouseClock

.segment	"DATA"

_mouseState:
	.byte	$50
	.byte	$64
	.byte	$FF

.segment	"BSS"

_mouseClock:
	.res	4,$00

; ---------------------------------------------------------------
; unsigned char *__near__ GetMouse (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_GetMouse: near

.segment	"SHADOW_RAM"

	lda     #$FF
	sta     _mouseState+2
	jsr     _clock
	jsr     pusheax
	lda     _mouseClock+3
	sta     sreg+1
	lda     _mouseClock+2
	sta     sreg
	ldx     _mouseClock+1
	lda     _mouseClock
	jsr     tossubeax
	jsr     shleax1
	sta     M0001
	cmp     #$1F
	bcc     L0002
	lda     #$00
	sta     M0001
L0002:	jsr     _clock
	sta     _mouseClock
	stx     _mouseClock+1
	ldy     sreg
	sty     _mouseClock+2
	ldy     sreg+1
	sty     _mouseClock+3
	lda     #$00
	jsr     _GetJoy
	sta     M0002
	and     #$04
	bne     L0018
	lda     _mouseState
	cmp     M0001
	bcc     L0015
	beq     L0015
	lda     M0001
	jmp     L0017
L0015:	lda     _mouseState
L0017:	eor     #$FF
	sec
	adc     _mouseState
	sta     _mouseState
	lda     _mouseState+2
	and     #$DF
	sta     _mouseState+2
L0018:	lda     M0002
	and     #$08
	bne     L001A
	lda     #$9F
	jsr     pusha0
	lda     _mouseState
	clc
	adc     M0001
	bcc     L0011
	ldx     #$01
L0011:	jsr     tosicmp
	bmi     L0007
	beq     L0007
	lda     _mouseState
	clc
	adc     M0001
	jmp     L0019
L0007:	lda     #$9F
L0019:	sta     _mouseState
	lda     _mouseState+2
	and     #$DF
	sta     _mouseState+2
L001A:	lda     M0002
	and     #$01
	bne     L001E
	lda     _mouseState+1
	cmp     M0001
	bcc     L001B
	beq     L001B
	lda     M0001
	jmp     L001D
L001B:	lda     _mouseState+1
L001D:	eor     #$FF
	sec
	adc     _mouseState+1
	sta     _mouseState+1
	lda     _mouseState+2
	and     #$DF
	sta     _mouseState+2
L001E:	lda     M0002
	and     #$02
	bne     L0020
	lda     #$C7
	jsr     pusha0
	lda     _mouseState+1
	clc
	adc     M0001
	bcc     L0013
	ldx     #$01
L0013:	jsr     tosicmp
	bmi     L000D
	beq     L000D
	lda     _mouseState+1
	clc
	adc     M0001
	jmp     L001F
L000D:	lda     #$C7
L001F:	sta     _mouseState+1
	lda     _mouseState+2
	and     #$DF
	sta     _mouseState+2
L0020:	lda     M0002
	and     #$10
	bne     L0021
	lda     _mouseState+2
	and     #$FE
	sta     _mouseState+2
L0021:	lda     M0002
	and     #$20
	bne     L0010
	lda     _mouseState+2
	and     #$FB
	sta     _mouseState+2
L0010:	lda     #<(_mouseState)
	ldx     #>(_mouseState)
	rts

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00

.endproc

