;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_OpenWEB
	.export		_CloseWEB
	.export		_HeaderWEB
	.export		_BodyWEB
	.export		_SendWEB
	.export		_RecvWEB

; ---------------------------------------------------------------
; void __near__ OpenWEB (unsigned int port, unsigned int timeOut)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_OpenWEB: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ CloseWEB (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_CloseWEB: near

.segment	"SHADOW_RAM"

	rts

.endproc

; ---------------------------------------------------------------
; void __near__ HeaderWEB (unsigned char *buffer, unsigned char length)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_HeaderWEB: near

.segment	"SHADOW_RAM"

	jsr     pusha
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ BodyWEB (unsigned char *buffer, unsigned char length)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_BodyWEB: near

.segment	"SHADOW_RAM"

	jsr     pusha
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ SendWEB (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SendWEB: near

.segment	"SHADOW_RAM"

	rts

.endproc

; ---------------------------------------------------------------
; unsigned char *__near__ RecvWEB (unsigned int timeOut)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_RecvWEB: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jmp     incsp2

.endproc

