;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_clock
	.export		_SlotTCP
	.export		_OpenTCP
	.export		_CloseTCP
	.export		_SendTCP
	.export		_RecvTCP

; ---------------------------------------------------------------
; void __near__ SlotTCP (unsigned char slot)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SlotTCP: near

.segment	"SHADOW_RAM"

	jsr     pusha
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ OpenTCP (unsigned char *svIP, unsigned int svPort)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_OpenTCP: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ CloseTCP (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_CloseTCP: near

.segment	"SHADOW_RAM"

	rts

.endproc

; ---------------------------------------------------------------
; void __near__ SendTCP (unsigned char *buffer, unsigned char length)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SendTCP: near

.segment	"SHADOW_RAM"

	jsr     pusha
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char *__near__ RecvTCP (unsigned int timeOut)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_RecvTCP: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     _clock
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	jsr     axulong
	jsr     tosaddeax
	sta     M0001
	stx     M0001+1
	ldy     sreg
	sty     M0001+2
	ldy     sreg+1
	sty     M0001+3
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	4,$00

.endproc

