;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.import		___clocks_per_sec
	.import		_clock
	.export		_easyProt
	.export		_easyLive
	.export		_easySlot
	.export		_EasyHost
	.export		_EasyJoin
	.export		_EasySend
	.export		_EasyRecv
	.export		_EasyQuit
	.import		_OpenTCP
	.import		_CloseTCP
	.import		_SendTCP
	.import		_RecvTCP
	.import		_OpenUDP
	.import		_CloseUDP
	.import		_SendUDP
	.import		_RecvUDP
	.export		_easyTimer
	.export		_easyBuffer
	.export		_easyIP

.segment	"DATA"

_easyProt:
	.byte	$00
_easyLive:
	.byte	$00
_easySlot:
	.byte	$00
_easyIP:
	.byte	$C7
	.byte	$2F
	.byte	$C4
	.byte	$6A

.segment	"BSS"

_easyTimer:
	.res	4,$00
_easyBuffer:
	.res	256,$00

; ---------------------------------------------------------------
; unsigned char __near__ EasyHost (unsigned char protocol, unsigned char slots, unsigned int *ID, unsigned int *PASS)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EasyHost: near

.segment	"CODE"

	jsr     pushax
	jsr     _clock
	jsr     pusheax
	jsr     ___clocks_per_sec
	jsr     shleax1
	jsr     tosaddeax
	sta     _easyTimer
	stx     _easyTimer+1
	ldy     sreg
	sty     _easyTimer+2
	ldy     sreg+1
	sty     _easyTimer+3
	ldy     #$05
	lda     (c_sp),y
	sta     _easyProt
	lda     #$0B
	sta     _easyBuffer
	dey
	lda     (c_sp),y
	sta     _easyBuffer+1
	lda     _easyProt
	cmp     #$01
	bne     L0002
	lda     #<(_easyIP)
	ldx     #>(_easyIP)
	jsr     pushax
	ldx     #$05
	lda     #$DB
	jsr     _OpenTCP
	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	lda     #$02
	jsr     _SendTCP
	jmp     L0004
L0002:	lda     #<(_easyIP)
	ldx     #>(_easyIP)
	jsr     pushax
	ldx     #$05
	lda     #$DB
	jsr     pushax
	jsr     _clock
	ldx     #$00
	jsr     push0ax
	lda     #$DB
	ldx     #$05
	jsr     tosadd0ax
	jsr     _OpenUDP
	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	lda     #$02
	jsr     _SendUDP
L0004:	ldx     #$00
	lda     _easyProt
	cmp     #$01
	bne     L000F
	txa
	jsr     _RecvTCP
	jmp     L0011
L000F:	txa
	jsr     _RecvUDP
L0011:	sta     M0001
	stx     M0001+1
	lda     M0001
	ora     M0001+1
	beq     L0009
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$0B
	bne     L0009
	lda     #$01
	sta     _easyLive
	sty     _easySlot
	ldy     #$03
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	lda     M0001
	ldx     M0001+1
	ldy     #$02
	jsr     ldaxidx
	ldy     #$00
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
	jsr     ldax0sp
	sta     sreg
	stx     sreg+1
	lda     M0001
	ldx     M0001+1
	ldy     #$04
	jsr     ldaxidx
	ldy     #$00
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
	ldx     #$00
	txa
	jmp     incsp6
L0009:	jsr     _clock
	jsr     pusheax
	lda     _easyTimer+3
	sta     sreg+1
	lda     _easyTimer+2
	sta     sreg
	ldx     _easyTimer+1
	lda     _easyTimer
	jsr     tosugeeax
	jeq     L0004
	ldx     #$00
	lda     #$03
	jmp     incsp6

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ EasyJoin (unsigned char protocol, unsigned int *ID, unsigned int *PASS)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EasyJoin: near

.segment	"CODE"

	jsr     pushax
	jsr     _clock
	jsr     pusheax
	jsr     ___clocks_per_sec
	jsr     shleax1
	jsr     tosaddeax
	sta     _easyTimer
	stx     _easyTimer+1
	ldy     sreg
	sty     _easyTimer+2
	ldy     sreg+1
	sty     _easyTimer+3
	ldy     #$04
	lda     (c_sp),y
	sta     _easyProt
	lda     #$0C
	sta     _easyBuffer
	dey
	jsr     ldaxysp
	jsr     ldaxi
	sta     _easyBuffer+1
	stx     _easyBuffer+1+1
	jsr     ldax0sp
	jsr     ldaxi
	sta     _easyBuffer+3
	stx     _easyBuffer+3+1
	lda     _easyProt
	cmp     #$01
	bne     L0002
	lda     #<(_easyIP)
	ldx     #>(_easyIP)
	jsr     pushax
	ldx     #$05
	lda     #$DB
	jsr     _OpenTCP
	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	lda     #$05
	jsr     _SendTCP
	jmp     L0004
L0002:	lda     #<(_easyIP)
	ldx     #>(_easyIP)
	jsr     pushax
	ldx     #$05
	lda     #$DB
	jsr     pushax
	jsr     _clock
	ldx     #$00
	jsr     push0ax
	lda     #$DB
	ldx     #$05
	jsr     tosadd0ax
	jsr     _OpenUDP
	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	lda     #$05
	jsr     _SendUDP
L0004:	ldx     #$00
	lda     _easyProt
	cmp     #$01
	bne     L0011
	txa
	jsr     _RecvTCP
	jmp     L0016
L0011:	txa
	jsr     _RecvUDP
L0016:	sta     M0001
	stx     M0001+1
	lda     M0001
	ora     M0001+1
	beq     L000B
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	cmp     #$01
	beq     L0005
	cmp     #$02
	beq     L0005
	cmp     #$0C
	bne     L000B
	lda     #$01
	sta     _easyLive
	lda     M0001
	ldx     M0001+1
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     _easySlot
	ldx     #$00
	txa
	jmp     incsp5
L000B:	jsr     _clock
	jsr     pusheax
	lda     _easyTimer+3
	sta     sreg+1
	lda     _easyTimer+2
	sta     sreg
	ldx     _easyTimer+1
	lda     _easyTimer
	jsr     tosugeeax
	beq     L0004
	ldx     #$00
	lda     #$03
L0005:	jmp     incsp5

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; void __near__ EasySend (unsigned char *buffer, unsigned char len)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EasySend: near

.segment	"CODE"

	jsr     pusha
	lda     _easyLive
	beq     L0004
	lda     #$0D
	sta     _easyBuffer
	ldy     #$00
	lda     (c_sp),y
	sta     _easyBuffer+1
	lda     #<(_easyBuffer+2)
	ldx     #>(_easyBuffer+2)
	jsr     pushax
	ldy     #$06
	jsr     pushwysp
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     _memcpy
	lda     _easyProt
	cmp     #$01
	bne     L0003
	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     #$02
	jsr     _SendTCP
	jmp     incsp3
L0003:	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     #$02
	jsr     _SendUDP
L0004:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char *__near__ EasyRecv (unsigned char timeout, unsigned char *len)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EasyRecv: near

.segment	"CODE"

	jsr     pushax
	lda     _easyLive
	beq     L000D
	lda     _easyProt
	cmp     #$01
	bne     L0003
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     _RecvTCP
	jmp     L000E
L0003:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     _RecvUDP
L000E:	sta     M0001
	stx     M0001+1
	lda     M0001
	ora     M0001+1
	beq     L0005
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$0E
	bne     L0005
	jsr     ldax0sp
	sta     sreg
	stx     sreg+1
	lda     M0001
	ldx     M0001+1
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sreg),y
	lda     M0001
	ldx     M0001+1
	jsr     incax2
	jmp     incsp3
L0005:	jsr     ldptr10sp
	lda     #$00
	tay
	sta     (ptr1),y
L000D:	tax
	jmp     incsp3

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; void __near__ EasyQuit (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EasyQuit: near

.segment	"CODE"

	lda     _easyLive
	beq     L0004
	lda     #$00
	sta     _easyLive
	lda     #$0F
	sta     _easyBuffer
	lda     _easyProt
	cmp     #$01
	bne     L0003
	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	lda     #$01
	jsr     _SendTCP
	jmp     _CloseTCP
L0003:	lda     #<(_easyBuffer)
	ldx     #>(_easyBuffer)
	jsr     pushax
	lda     #$01
	jsr     _SendUDP
	jmp     _CloseUDP
L0004:	rts

.endproc

