;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_GetURL
	.export		_ReadURL

; ---------------------------------------------------------------
; void __near__ GetURL (unsigned char *url)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_GetURL: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char *__near__ ReadURL (unsigned char size, unsigned int timeOut)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ReadURL: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jmp     incsp3

.endproc

