// Code generated by cmd/navgen. DO NOT EDIT.

package game

// Track is one entry of the map list the clients ship.
type Track struct {
	Name    string
	NumWays byte
}

// Tracks is indexed by the map id carried in SV_INFO and SV_EVENT,
// matching mapList[] in projects/slicks/src/slicks.c.
var Tracks = []Track{
	{Name: "arizona", NumWays: 6},
	{Name: "arto", NumWays: 5},
	{Name: "cramp", NumWays: 8},
	{Name: "freeway", NumWays: 5},
	{Name: "gta", NumWays: 5},
	{Name: "island", NumWays: 4},
	{Name: "mtcarlo", NumWays: 7},
	{Name: "rally", NumWays: 5},
	{Name: "river", NumWays: 5},
	{Name: "stadium", NumWays: 4},
}
