;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_IntersectSegments
	.export		_IntersectSegmentPolygon
	.export		_PointInsidePolygon

; ---------------------------------------------------------------
; unsigned char __near__ IntersectSegments (int seg1X1, int seg1Y1, int seg1X2, int seg1Y2, int seg2X1, int seg2Y1, int seg2X2, int seg2Y2, int *intX, int *intY)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_IntersectSegments: near

.segment	"CODE"

	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	sec
	ldy     #$12
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     axlong
	sta     M0001
	stx     M0001+1
	ldy     sreg
	sty     M0001+2
	ldy     sreg+1
	sty     M0001+3
	ldy     #$0D
	jsr     ldaxysp
	sec
	ldy     #$10
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     axlong
	sta     M0002
	stx     M0002+1
	ldy     sreg
	sty     M0002+2
	ldy     sreg+1
	sty     M0002+3
	ldy     #$07
	jsr     ldaxysp
	sec
	ldy     #$0A
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     axlong
	sta     M0003
	stx     M0003+1
	ldy     sreg
	sty     M0003+2
	ldy     sreg+1
	sty     M0003+3
	ldy     #$05
	jsr     ldaxysp
	sec
	ldy     #$08
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     axlong
	sta     M0004
	stx     M0004+1
	ldy     sreg
	sty     M0004+2
	ldy     sreg+1
	sty     M0004+3
	lda     M0001+3
	sta     sreg+1
	lda     M0001+2
	sta     sreg
	ldx     M0001+1
	lda     M0001
	jsr     pusheax
	lda     M0004+3
	sta     sreg+1
	lda     M0004+2
	sta     sreg
	ldx     M0004+1
	lda     M0004
	jsr     tosmuleax
	jsr     pusheax
	lda     M0002+3
	sta     sreg+1
	lda     M0002+2
	sta     sreg
	ldx     M0002+1
	lda     M0002
	jsr     pusheax
	lda     M0003+3
	sta     sreg+1
	lda     M0003+2
	sta     sreg
	ldx     M0003+1
	lda     M0003
	jsr     tosmuleax
	jsr     tossubeax
	sta     M0005
	stx     M0005+1
	ldy     sreg
	sty     M0005+2
	ldy     sreg+1
	sty     M0005+3
	lda     M0005+3
	sta     sreg+1
	lda     M0005+2
	sta     sreg
	ldx     M0005+1
	lda     M0005
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	sta     sreg
	tax
	jsr     toseqeax
	beq     L0002
	ldx     #$00
	txa
	jmp     L0001
L0002:	ldy     #$11
	jsr     ldaxysp
	sec
	ldy     #$08
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     M0003+3
	sta     sreg+1
	lda     M0003+2
	sta     sreg
	ldx     M0003+1
	lda     M0003
	jsr     toslong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$17
	jsr     ldaxysp
	sec
	ldy     #$0E
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     M0004+3
	sta     sreg+1
	lda     M0004+2
	sta     sreg
	ldx     M0004+1
	lda     M0004
	jsr     toslong
	jsr     tosmuleax
	jsr     tossubeax
	sta     M0006
	stx     M0006+1
	ldy     sreg
	sty     M0006+2
	ldy     sreg+1
	sty     M0006+3
	ldy     #$11
	jsr     ldaxysp
	sec
	ldy     #$08
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     M0001+3
	sta     sreg+1
	lda     M0001+2
	sta     sreg
	ldx     M0001+1
	lda     M0001
	jsr     toslong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$17
	jsr     ldaxysp
	sec
	ldy     #$0E
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     M0002+3
	sta     sreg+1
	lda     M0002+2
	sta     sreg
	ldx     M0002+1
	lda     M0002
	jsr     toslong
	jsr     tosmuleax
	jsr     tossubeax
	sta     M0007
	stx     M0007+1
	ldy     sreg
	sty     M0007+2
	ldy     sreg+1
	sty     M0007+3
	lda     M0006+3
	sta     sreg+1
	lda     M0006+2
	sta     sreg
	ldx     M0006+1
	lda     M0006
	jsr     pusheax
	lda     #$64
	ldx     #$00
	jsr     tosmul0ax
	jsr     pusheax
	lda     M0005+3
	sta     sreg+1
	lda     M0005+2
	sta     sreg
	ldx     M0005+1
	lda     M0005
	jsr     tosdiveax
	sta     M0008
	stx     M0008+1
	ldy     sreg
	sty     M0008+2
	ldy     sreg+1
	sty     M0008+3
	lda     M0008+3
	asl     a
	bcs     L0009
	lda     M0008+3
	sta     sreg+1
	lda     M0008+2
	sta     sreg
	ldx     M0008+1
	lda     M0008
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	sta     sreg
	lda     #$65
	ldx     #$00
	jsr     tosgeeax
	beq     L0003
L0009:	ldx     #$00
	txa
	jmp     L0001
L0003:	lda     M0007+3
	sta     sreg+1
	lda     M0007+2
	sta     sreg
	ldx     M0007+1
	lda     M0007
	jsr     pusheax
	lda     #$64
	ldx     #$00
	jsr     tosmul0ax
	jsr     pusheax
	lda     M0005+3
	sta     sreg+1
	lda     M0005+2
	sta     sreg
	ldx     M0005+1
	lda     M0005
	jsr     tosdiveax
	sta     M0009
	stx     M0009+1
	ldy     sreg
	sty     M0009+2
	ldy     sreg+1
	sty     M0009+3
	lda     M0009+3
	asl     a
	bcs     L000A
	lda     M0009+3
	sta     sreg+1
	lda     M0009+2
	sta     sreg
	ldx     M0009+1
	lda     M0009
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	sta     sreg
	lda     #$65
	ldx     #$00
	jsr     tosgeeax
	beq     L0006
L000A:	ldx     #$00
	txa
	jmp     L0001
L0006:	ldy     #$05
	jsr     pushwysp
	ldy     #$17
	jsr     pushwysp
	lda     M0008+3
	sta     sreg+1
	lda     M0008+2
	sta     sreg
	ldx     M0008+1
	lda     M0008
	jsr     pusheax
	lda     M0001+3
	sta     sreg+1
	lda     M0001+2
	sta     sreg
	ldx     M0001+1
	lda     M0001
	jsr     tosmuleax
	jsr     pusheax
	lda     #$64
	ldx     #$00
	jsr     tosdiv0ax
	jsr     toslong
	jsr     tosaddeax
	ldy     #$00
	jsr     staxspidx
	jsr     pushw0sp
	ldy     #$15
	jsr     pushwysp
	lda     M0008+3
	sta     sreg+1
	lda     M0008+2
	sta     sreg
	ldx     M0008+1
	lda     M0008
	jsr     pusheax
	lda     M0002+3
	sta     sreg+1
	lda     M0002+2
	sta     sreg
	ldx     M0002+1
	lda     M0002
	jsr     tosmuleax
	jsr     pusheax
	lda     #$64
	ldx     #$00
	jsr     tosdiv0ax
	jsr     toslong
	jsr     tosaddeax
	ldy     #$00
	jsr     staxspidx
	ldx     #$00
	lda     #$01
L0001:	ldy     #$14
	jmp     addysp

.segment	"BSS"

M0001:
	.res	4,$00
M0002:
	.res	4,$00
M0003:
	.res	4,$00
M0004:
	.res	4,$00
M0005:
	.res	4,$00
M0006:
	.res	4,$00
M0007:
	.res	4,$00
M0008:
	.res	4,$00
M0009:
	.res	4,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ IntersectSegmentPolygon (int segX1, int segY1, int segX2, int segY2, unsigned char polyN, int *polyX, int *polyY, unsigned char *intI, int *intX, int *intY)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_IntersectSegmentPolygon: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     M0002
	lda     #$01
	sta     M0001
	ldx     #$00
L0010:	lda     M0001
	ldy     #$0A
	cmp     (c_sp),y
	jcs     L0012
	ldy     #$14
	jsr     pushwysp
	ldy     #$14
	jsr     pushwysp
	ldy     #$14
	jsr     pushwysp
	ldy     #$14
	jsr     pushwysp
	ldx     #$00
	lda     M0001
	jsr     decax1
	jsr     aslax1
	clc
	ldy     #$10
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	ldx     #$00
	lda     M0001
	jsr     decax1
	jsr     aslax1
	clc
	ldy     #$10
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L000C
	inx
	clc
L000C:	ldy     #$14
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L000D
	inx
	clc
L000D:	ldy     #$14
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	lda     #<(M0003)
	ldx     #>(M0003)
	jsr     pushax
	lda     #<(M0004)
	ldx     #>(M0004)
	jsr     _IntersectSegments
	tax
	beq     L0011
	ldy     #$05
	jsr     ldptr1ysp
	ldy     M0002
	lda     M0001
	sta     (ptr1),y
	ldx     #$00
	lda     M0002
	asl     a
	bcc     L000E
	inx
	clc
L000E:	ldy     #$02
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     M0003
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     M0003+1
	sta     (ptr1),y
	ldx     #$00
	lda     M0002
	asl     a
	bcc     L000F
	inx
	clc
L000F:	dey
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     M0004
	dey
	sta     (ptr1),y
	iny
	lda     M0004+1
	sta     (ptr1),y
	inc     M0002
	ldx     #$00
L0011:	inc     M0001
	jmp     L0010
L0012:	lda     M0002
	ldy     #$13
	jmp     addysp

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	2,$00
M0004:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ PointInsidePolygon (int pX, int pY, unsigned char polyN, int *polyX, int *polyY)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_PointInsidePolygon: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     M0003
	sta     M0001
	ldy     #$04
	lda     (c_sp),y
	sec
	sbc     #$01
L0010:	sta     M0002
	ldx     #$00
	lda     M0001
	ldy     #$04
	cmp     (c_sp),y
	jcs     L0019
	lda     M0001
	asl     a
	bcc     L0011
	inx
	clc
L0011:	ldy     #$00
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	ldy     #$08
	jsr     ldaxysp
	jsr     tosgtax
	jsr     pusha0
	lda     M0002
	asl     a
	bcc     L0012
	ldx     #$01
	clc
L0012:	ldy     #$02
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	ldy     #$0A
	jsr     ldaxysp
	jsr     tosgtax
	jsr     tosicmp0
	jeq     L0004
	ldx     #$00
	lda     M0002
	asl     a
	bcc     L0013
	inx
	clc
L0013:	ldy     #$02
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L0014
	inx
	clc
L0014:	ldy     #$04
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     ldaxi
	jsr     tossubax
	jsr     axlong
	sta     M0004
	stx     M0004+1
	ldy     sreg
	sty     M0004+2
	ldy     sreg+1
	sty     M0004+3
	lda     M0004+3
	sta     sreg+1
	lda     M0004+2
	sta     sreg
	ldx     M0004+1
	lda     M0004
	jsr     pusheax
	ldy     #$0C
	jsr     pushwysp
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L0015
	inx
	clc
L0015:	ldy     #$06
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     ldaxi
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	sta     M0004
	stx     M0004+1
	ldy     sreg
	sty     M0004+2
	ldy     sreg+1
	sty     M0004+3
	lda     M0004+3
	sta     sreg+1
	lda     M0004+2
	sta     sreg
	ldx     M0004+1
	lda     M0004
	jsr     pusheax
	ldx     #$00
	lda     M0002
	asl     a
	bcc     L0016
	inx
	clc
L0016:	ldy     #$04
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L0017
	inx
	clc
L0017:	ldy     #$06
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     ldaxi
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	sta     M0004
	stx     M0004+1
	ldy     sreg
	sty     M0004+2
	ldy     sreg+1
	sty     M0004+3
	ldy     #$0A
	jsr     pushwysp
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L0018
	inx
	clc
L0018:	ldy     #$04
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushw
	lda     M0004+3
	sta     sreg+1
	lda     M0004+2
	sta     sreg
	ldx     M0004+1
	lda     M0004
	jsr     toslong
	jsr     tosaddeax
	jsr     toslong
	jsr     toslteax
	beq     L0004
	lda     M0003
	jsr     bnega
	sta     M0003
L0004:	lda     M0001
	inc     M0001
	jmp     L0010
L0019:	lda     M0003
	ldy     #$09
	jmp     addysp

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00
M0004:
	.res	4,$00

.endproc

