// navgen regenerates internal/game/navdata.go from the game's .nav files.
//
// The server validates lap progress against each track's waypoint count, which
// only exists in the .nav files the client loads. Rather than parse them at
// runtime -- the server has no reason to depend on the game tree -- the count is
// baked into a small generated table.
//
//	go run ./cmd/navgen ../projects/slicks/navigation > internal/game/navdata.go
//
// A .nav file is the flat image of the globals in navigation.c, read in
// declaration order (navigation.c:58):
//
//	lineupX[4]   uint16   offset  0
//	lineupY[4]   uint16   offset  8
//	lineupAng[4] uint16   offset 16
//	numWays      uint8    offset 24
//	ways[8]      Waypoint offset 25   (int x, int y, signed char v[2][2] = 8 bytes)
//	numRamps     uint8    offset 89
//	ramps[3]     Ramp     offset 90   (int x[2], y[2] = 8 bytes)
//	terrain[736]          offset 114
//
// which totals the 850 bytes navigation.c reads.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	numWaysOffset = 24
	navFileSize   = 850
	maxWaypoints  = 8
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: navgen <navigation dir>")
		os.Exit(2)
	}

	paths, err := filepath.Glob(filepath.Join(os.Args[1], "*.nav"))
	if err != nil || len(paths) == 0 {
		fmt.Fprintf(os.Stderr, "navgen: no .nav files in %s\n", os.Args[1])
		os.Exit(1)
	}
	// Sorted order has to match mapList[] in projects/slicks/src/slicks.c,
	// because the wire protocol identifies a map by its index in that list.
	sort.Strings(paths)

	type track struct {
		name    string
		numWays byte
	}
	tracks := make([]track, 0, len(paths))

	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "navgen: %v\n", err)
			os.Exit(1)
		}
		if len(data) != navFileSize {
			fmt.Fprintf(os.Stderr, "navgen: %s is %d bytes, expected %d\n",
				path, len(data), navFileSize)
			os.Exit(1)
		}
		ways := data[numWaysOffset]
		if ways == 0 || ways > maxWaypoints {
			fmt.Fprintf(os.Stderr, "navgen: %s reports %d waypoints, expected 1..%d\n",
				path, ways, maxWaypoints)
			os.Exit(1)
		}
		name := strings.TrimSuffix(filepath.Base(path), ".nav")
		tracks = append(tracks, track{name: name, numWays: ways})
	}

	var out strings.Builder
	out.WriteString("// Code generated by cmd/navgen. DO NOT EDIT.\n\n")
	out.WriteString("package game\n\n")
	out.WriteString("// Track is one entry of the map list the clients ship.\n")
	out.WriteString("type Track struct {\n\tName    string\n\tNumWays byte\n}\n\n")
	out.WriteString("// Tracks is indexed by the map id carried in SV_INFO and SV_EVENT,\n")
	out.WriteString("// matching mapList[] in projects/slicks/src/slicks.c.\n")
	out.WriteString("var Tracks = []Track{\n")
	for _, t := range tracks {
		fmt.Fprintf(&out, "\t{Name: %q, NumWays: %d},\n", t.name, t.numWays)
	}
	out.WriteString("}\n")

	fmt.Print(out.String())
}
