;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_bzero
	.export		_ClearBitmap

; ---------------------------------------------------------------
; void __near__ ClearBitmap (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ClearBitmap: near

.segment	"SHADOW_RAM"

	ldx     #$A0
	lda     #$10
	jsr     pushax
	ldx     #$1F
	lda     #$40
	jsr     _bzero
	ldx     #$70
	lda     #$10
	jsr     pushax
	ldx     #$1F
	lda     #$40
	jmp     _bzero

.endproc

