;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_StartDLI
	.import		_StartVBI
	.import		_doubleBuffer
	.export		_InitBitmap

; ---------------------------------------------------------------
; void __near__ InitBitmap (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_InitBitmap: near

.segment	"SHADOW_RAM"

	lda     #$00
	sta     $0058
	sta     $0058+1
	sta     $005E
	sta     $005E+1
	sta     $005D
	lda     #$1A
	sta     $022F
	jsr     _StartDLI
	jsr     _StartVBI
	lda     #$01
	sta     _doubleBuffer
	rts

.endproc

