;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_bmpPalette
	.import		_Decrunch
	.export		_LoadBitmap
	.import		_FileOpen
	.import		_FileRead

; ---------------------------------------------------------------
; void __near__ LoadBitmap (char *filename)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LoadBitmap: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     ldax0sp
	jsr     _FileOpen
	stx     tmp1
	ora     tmp1
	beq     L0002
	lda     #<(_bmpPalette)
	ldx     #>(_bmpPalette)
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     _FileRead
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     _FileRead
	ldx     #$A0
	lda     #$08
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     _FileRead
	lda     #$08
	clc
	adc     M0001
	pha
	lda     #$A0
	adc     M0001+1
	tax
	pla
	jsr     _Decrunch
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     _FileRead
	ldx     #$70
	lda     #$08
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     _FileRead
	lda     #$08
	clc
	adc     M0001
	pha
	lda     #$70
	adc     M0001+1
	tax
	pla
	jsr     _Decrunch
L0002:	jmp     incsp2

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

