;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_BitmapDLIST
	.import		_SetPalette
	.import		_bitmapVBI
	.import		_chrRows
	.import		_bmpPalette
	.export		_ShowBitmap

; ---------------------------------------------------------------
; void __near__ ShowBitmap (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ShowBitmap: near

.segment	"SHADOW_RAM"

	lda     #$80
	sta     _chrRows
	jsr     _BitmapDLIST
	lda     #$01
	sta     _bitmapVBI
	lda     $022F
	ora     #$20
	sta     $022F
	lda     #<(_bmpPalette)
	ldx     #>(_bmpPalette)
	jmp     _SetPalette

.endproc

