;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.export		_FreeChunk
	.export		_chunkBuf
	.export		_chunkPtr
	.import		_GuruMeditation
	.export		_CheckMemory

.segment	"DATA"

_chunkPtr:
	.addr	_chunkBuf

.segment	"RODATA"

S0002:
	.byte	$43,$68,$75,$6E,$6B,$73,$00

.segment	"BSS"

_chunkBuf:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ FreeChunk (unsigned char *chunk)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_FreeChunk: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$00
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	bne     L0009
	lda     #>(_chunkBuf)
	sta     _chunkPtr+1
	lda     #<(_chunkBuf)
	sta     _chunkPtr
	jmp     incsp2
L0009:	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     M0001
	lda     _chunkPtr
	ldx     _chunkPtr+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     M0001
	bcc     L0006
	inx
L0006:	jsr     tosicmp
	beq     L0005
	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     M0001
	bcc     L0007
	inx
L0007:	jsr     pushax
	lda     #$01
	sec
	sbc     M0001
	ldx     #$00
	bcs     L0008
	dex
L0008:	jsr     _memcpy
L0005:	lda     M0001
	eor     #$FF
	sec
	adc     _chunkPtr
	sta     _chunkPtr
	lda     #$FF
	adc     _chunkPtr+1
	sta     _chunkPtr+1
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ CheckMemory (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_CheckMemory: near

.segment	"SHADOW_RAM"

	lda     _chunkPtr
	sec
	sbc     #<(_chunkBuf+1)
	sta     tmp1
	lda     _chunkPtr+1
	sbc     #>(_chunkBuf+1)
	ora     tmp1
	bcc     L0002
	beq     L0002
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	lda     _chunkPtr
	sec
	sbc     #<(_chunkBuf+1)
	pha
	lda     _chunkPtr+1
	sbc     #>(_chunkBuf+1)
	tax
	pla
	jmp     _GuruMeditation
L0002:	rts

.endproc

