;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.export		_GetChunk
	.import		_chunkPtr
	.import		_CheckMemory

; ---------------------------------------------------------------
; unsigned char *__near__ GetChunk (unsigned char x, unsigned char y, unsigned char w, unsigned char h)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_GetChunk: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     _chunkPtr+1
	sta     M0003+1
	lda     _chunkPtr
	sta     M0003
	ldx     _chunkPtr+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	inc     _chunkPtr
	bne     L0002
	inc     _chunkPtr+1
L0002:	lda     _chunkPtr+1
	sta     ptr1+1
	lda     _chunkPtr
	sta     ptr1
	ldy     #$02
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	inc     _chunkPtr
	bne     L0003
	inc     _chunkPtr+1
L0003:	lda     _chunkPtr+1
	sta     ptr1+1
	lda     _chunkPtr
	sta     ptr1
	iny
	lda     (c_sp),y
	dey
	sta     (ptr1),y
	inc     _chunkPtr
	bne     L0004
	inc     _chunkPtr+1
L0004:	lda     _chunkPtr+1
	sta     ptr1+1
	lda     _chunkPtr
	sta     ptr1
	lda     (c_sp),y
	sta     (ptr1),y
	inc     _chunkPtr
	bne     L0005
	inc     _chunkPtr+1
L0005:	lda     #$02
	clc
	adc     _chunkPtr
	sta     _chunkPtr
	bcc     L0006
	inc     _chunkPtr+1
L0006:	iny
	lda     (c_sp),y
	lsr     a
	lsr     a
	sta     M0002
	lda     #$00
	sta     M0001
L0013:	lda     M0001
	ldy     #$00
	cmp     (c_sp),y
	bcs     L0014
	lda     _chunkPtr
	ldx     _chunkPtr+1
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	clc
	adc     M0001
	bcc     L000F
	inx
L000F:	jsr     pushax
	lda     #$28
	jsr     tosumula0
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	sta     ptr1
	lda     #$A0
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$05
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0011
	inx
L0011:	jsr     pushax
	ldx     #$00
	lda     M0002
	jsr     _memcpy
	lda     M0002
	clc
	adc     _chunkPtr
	sta     _chunkPtr
	lda     #$00
	adc     _chunkPtr+1
	sta     _chunkPtr+1
	inc     M0001
	jmp     L0013
L0014:	sty     M0001
L0015:	lda     M0001
	ldy     #$00
	cmp     (c_sp),y
	bcs     L000C
	lda     _chunkPtr
	ldx     _chunkPtr+1
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	clc
	adc     M0001
	bcc     L0010
	inx
L0010:	jsr     pushax
	lda     #$28
	jsr     tosumula0
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	sta     ptr1
	lda     #$70
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$05
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0012
	inx
L0012:	jsr     pushax
	ldx     #$00
	lda     M0002
	jsr     _memcpy
	lda     M0002
	clc
	adc     _chunkPtr
	sta     _chunkPtr
	lda     #$00
	adc     _chunkPtr+1
	sta     _chunkPtr+1
	inc     M0001
	jmp     L0015
L000C:	lda     M0003
	ldx     M0003+1
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     _chunkPtr
	sec
	sbc     M0003
	pha
	lda     _chunkPtr+1
	sbc     M0003+1
	tax
	pla
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	jsr     _CheckMemory
	lda     M0003
	ldx     M0003+1
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	2,$00

.endproc

