;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_LoadChunks
	.import		_FileOpen
	.import		_FileRead
	.import		_FileClose
	.import		_chunkPtr
	.import		_CheckMemory

; ---------------------------------------------------------------
; unsigned char __near__ LoadChunks (unsigned char **chunks, char *filename)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LoadChunks: near

.segment	"SHADOW_RAM"

	jsr     pushax
	lda     #$00
	sta     M0002
	jsr     ldax0sp
	jsr     _FileOpen
	stx     tmp1
	ora     tmp1
	beq     L0002
	lda     _chunkPtr
	ldx     _chunkPtr+1
	jsr     pushax
	ldx     #$FF
	txa
	jsr     _FileRead
	jsr     _FileClose
	lda     _chunkPtr+1
	sta     ptr1+1
	lda     _chunkPtr
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	sta     M0002
	inc     _chunkPtr
	bne     L0003
	inc     _chunkPtr+1
L0003:	sty     M0001
L000A:	lda     M0001
	cmp     M0002
	bcs     L0005
	ldx     #$00
	lda     M0001
	asl     a
	bcc     L0009
	inx
	clc
L0009:	ldy     #$02
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     _chunkPtr
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     _chunkPtr+1
	sta     (ptr1),y
	lda     _chunkPtr
	ldx     _chunkPtr+1
	ldy     #$05
	jsr     ldaxidx
	clc
	adc     _chunkPtr
	sta     _chunkPtr
	txa
	adc     _chunkPtr+1
	sta     _chunkPtr+1
	inc     M0001
	jmp     L000A
L0005:	jsr     _CheckMemory
L0002:	ldx     #$00
	lda     M0002
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	2,$00

.endproc

