;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.export		_SetChunk

; ---------------------------------------------------------------
; void __near__ SetChunk (unsigned char *chunk, unsigned char x, unsigned char y)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SetChunk: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     M0001
	ldy     #$03
	jsr     ldaxysp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     M0002
	lda     M0001
	lsr     a
	lsr     a
	sta     M0004
	ldy     #$03
	jsr     ldaxysp
	jsr     incax6
	sta     M0005
	stx     M0005+1
	lda     #$00
	sta     M0003
L000E:	lda     M0003
	cmp     M0002
	bcs     L000F
	ldx     #$00
	lda     (c_sp,x)
	clc
	adc     M0003
	bcc     L000A
	inx
L000A:	jsr     pushax
	lda     #$28
	jsr     tosmula0
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	sta     ptr1
	lda     #$A0
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L000C
	inx
L000C:	jsr     pushax
	lda     M0005
	ldx     M0005+1
	jsr     pushax
	ldx     #$00
	lda     M0004
	jsr     _memcpy
	lda     M0004
	clc
	adc     M0005
	sta     M0005
	lda     #$00
	adc     M0005+1
	sta     M0005+1
	inc     M0003
	jmp     L000E
L000F:	lda     #$00
	sta     M0003
L0010:	lda     M0003
	cmp     M0002
	bcs     L0007
	ldx     #$00
	lda     (c_sp,x)
	clc
	adc     M0003
	bcc     L000B
	inx
L000B:	jsr     pushax
	lda     #$28
	jsr     tosmula0
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	sta     ptr1
	lda     #$70
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L000D
	inx
L000D:	jsr     pushax
	lda     M0005
	ldx     M0005+1
	jsr     pushax
	ldx     #$00
	lda     M0004
	jsr     _memcpy
	lda     M0004
	clc
	adc     M0005
	sta     M0005
	lda     #$00
	adc     M0005+1
	sta     M0005+1
	inc     M0003
	jmp     L0010
L0007:	jmp     incsp4

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00
M0004:
	.res	1,$00
M0005:
	.res	2,$00

.endproc

