;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_imul8x8r16
	.export		_dot

; ---------------------------------------------------------------
; int __near__ dot (signed char *v1, signed char *v2)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_dot: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	jsr     ldaidx
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	ldy     #$00
	jsr     ldaidx
	jsr     _imul8x8r16
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     incax1
	ldy     #$00
	jsr     ldaidx
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	jsr     incax1
	ldy     #$00
	jsr     ldaidx
	jsr     _imul8x8r16
	jsr     tosaddax
	jmp     incsp4

.endproc

