;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_CropSprite

; ---------------------------------------------------------------
; void __near__ CropSprite (unsigned char index, unsigned char rows)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_CropSprite: near

.segment	"SHADOW_RAM"

	jsr     pusha
	jmp     incsp2

.endproc

