;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_bzero
	.import		_sprDLIs
	.import		_sprBank
	.import		_sprMask
	.import		_sprBegDLI
	.import		_sprCollide
	.import		_sprDrawn
	.export		_DisableSprite
	.import		_posPM0

; ---------------------------------------------------------------
; void __near__ DisableSprite (signed char index)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_DisableSprite: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	tax
	bmi     L0002
	lda     (c_sp),y
	tay
	lda     _sprDrawn,y
	beq     L0004
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     _sprBegDLI,y
	clc
	adc     #<(_posPM0)
	tay
	lda     #$00
	adc     #>(_posPM0)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     _sprDLIs
	jsr     _bzero
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _sprCollide,y
	tay
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _sprDrawn,y
L0004:	tax
	lda     (c_sp,x)
	bpl     L000D
	dex
L000D:	jsr     shrax2
	clc
	adc     #<(_sprBank)
	tay
	txa
	adc     #>(_sprBank)
	tax
	tya
	sta     sreg
	stx     sreg+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     ptr1
	lda     (c_sp),y
	tay
	lda     _sprMask,y
	eor     #$FF
	and     ptr1
	ldy     #$00
	sta     (sreg),y
	jmp     incsp1
L0002:	lda     #<(_sprCollide)
	ldx     #>(_sprCollide)
	jsr     pushax
	ldx     #$00
	lda     #$10
	jsr     _bzero
	lda     #<(_sprDrawn)
	ldx     #>(_sprDrawn)
	jsr     pushax
	ldx     #$00
	lda     #$10
	jsr     _bzero
	lda     #<(_sprBank)
	ldx     #>(_sprBank)
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     _bzero
	lda     #<(_posPM0)
	ldx     #>(_posPM0)
	jsr     pushax
	ldx     #$00
	lda     #$64
	jsr     _bzero
	jmp     incsp1

.endproc

