;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_sprBank
	.import		_sprMask
	.import		_collideEnabled
	.import		_sprCollide
	.import		_sprFlags
	.export		_sprScroll
	.export		_EnableSprite

.segment	"DATA"

_sprScroll:
	.byte	$01

; ---------------------------------------------------------------
; void __near__ EnableSprite (unsigned char index)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_EnableSprite: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	adc     #<(_sprBank)
	tay
	lda     #$00
	adc     #>(_sprBank)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     _sprMask,y
	jsr     tosora0
	ldy     #$00
	jsr     staspidx
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     _collideEnabled
	sta     _sprCollide,y
	lda     _sprScroll
	beq     L0004
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     #$01
	sta     _sprFlags,y
L0004:	jmp     incsp1

.endproc

