;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.import		_bzero
	.import		_StartDLI
	.import		_StartVBI
	.import		_spriteVBI
	.import		_sprRows
	.import		_sprPads
	.export		_sprDLIs
	.export		_sprMask
	.import		_sprColor
	.export		_sprData
	.export		_sprYOffset
	.import		_FileOpen
	.import		_FileRead
	.export		_LoadSprites
	.export		_sprCushion
	.export		_cushionLow
	.export		_cushionHigh

.segment	"DATA"

_sprCushion:
	.byte	$02
_sprMask:
	.byte	$01
	.byte	$02
	.byte	$04
	.byte	$08
	.byte	$01
	.byte	$02
	.byte	$04
	.byte	$08
	.byte	$01
	.byte	$02
	.byte	$04
	.byte	$08
	.byte	$01
	.byte	$02
	.byte	$04
	.byte	$08

.segment	"BSS"

_sprDLIs:
	.res	1,$00
_sprData:
	.res	2,$00
_sprYOffset:
	.res	1,$00
_sprBuffer:
	.res	360,$00
_cushionLow:
	.res	1,$00
_cushionHigh:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ LoadSprites (unsigned char *filename, const unsigned char *spriteColors)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LoadSprites: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _FileOpen
	stx     tmp1
	ora     tmp1
	beq     L0002
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     _FileRead
	lda     M0001
	cmp     #$69
	lda     M0001+1
	sbc     #$01
	bcc     L0003
	ldx     #$01
	lda     #$68
	sta     M0001
	stx     M0001+1
L0003:	lda     #<(_sprBuffer)
	ldx     #>(_sprBuffer)
	sta     _sprData
	stx     _sprData+1
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     _FileRead
L0002:	lda     #<(_sprColor)
	ldx     #>(_sprColor)
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	lda     #$10
	jsr     _memcpy
	lda     #$0A
	sta     _sprRows
	lda     #$03
	sta     _sprDLIs
	asl     a
	asl     a
	asl     a
	clc
	adc     #$02
	sta     _sprPads
	lda     #$07
	sta     _sprYOffset
	ldx     #$9C
	lda     #$00
	jsr     pushax
	ldx     #$04
	jsr     _bzero
	lda     #$98
	sta     $D407
	lda     #$03
	sta     $D01D
	lda     #$31
	sta     $026F
	lda     $022F
	ora     #$1A
	sta     $022F
	jsr     _StartDLI
	jsr     _StartVBI
	lda     #$01
	sta     _spriteVBI
	lda     #$0A
	sec
	sbc     _sprCushion
	sta     _cushionLow
	lda     #$00
	sec
	sbc     _cushionLow
	sta     _cushionHigh
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

