;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_LocateSprite
	.export		_spriteX
	.export		_spriteY

.segment	"BSS"

_spriteX:
	.res	1,$00
_spriteY:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ LocateSprite (unsigned int x, unsigned int y)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LocateSprite: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     shrax1
	ldy     #$2A
	jsr     incaxy
	sta     _spriteX
	ldy     #$00
	lda     (c_sp),y
	sta     _spriteY
	jmp     incsp4

.endproc

