;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_sprColor
	.export		_RecolorSprite

; ---------------------------------------------------------------
; void __near__ RecolorSprite (unsigned char index, unsigned char offset, unsigned char color)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_RecolorSprite: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	tax
	ldy     #$00
	lda     (c_sp),y
	sta     _sprColor,x
	jmp     incsp3

.endproc

