;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_sprDLIs
	.import		_sprBegDLI
	.import		_sprEndDLI
	.import		_sprLead
	.import		_sprSrc
	.import		_sprDst
	.import		_sprData
	.import		_sprYOffset
	.export		_collideEnabled
	.export		_sprCollide
	.export		_sprDrawn
	.export		_sprFlags
	.export		_sprFrame
	.export		_sprCollision
	.export		_sprX
	.export		_sprY
	.export		_SetSprite
	.import		_spriteX
	.import		_spriteY
	.export		_sc_dX
	.export		_sc_dY
	.import		_cushionLow
	.import		_cushionHigh
	.export		_SpriteCollisions
	.export		_ss_dli
	.export		_ss_lin
	.export		_ss_pmg
	.export		_ss_pos
	.export		_ss_off
	.export		_ss_src
	.export		_ss_dst

.segment	"DATA"

_collideEnabled:
	.byte	$01

.segment	"BSS"

_sprCollide:
	.res	16,$00
_sprDrawn:
	.res	16,$00
_sprFlags:
	.res	16,$00
_sprFrame:
	.res	16,$00
_sprCollision:
	.res	16,$00
_sprX:
	.res	16,$00
_sprY:
	.res	16,$00
_sc_dX:
	.res	1,$00
_sc_dY:
	.res	1,$00
_ss_dli:
	.res	1,$00
_ss_lin:
	.res	1,$00
_ss_pmg:
	.res	1,$00
_ss_pos:
	.res	1,$00
_ss_off:
	.res	1,$00
_ss_src:
	.res	2,$00
_ss_dst:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ SetSprite (unsigned char index, unsigned int frame)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SetSprite: near

.segment	"SHADOW_RAM"

	jsr     pushax
	lda     _spriteY
	cmp     _sprYOffset
	bcc     L0014
	beq     L0014
	sec
	sbc     _sprYOffset
	jmp     L0011
L0014:	lda     #$00
L0011:	sta     _ss_pos
	lsr     a
	lsr     a
	lsr     a
	sta     _ss_dli
	asl     a
	asl     a
	asl     a
	sta     _ss_lin
	lda     _ss_pos
	sec
	sbc     _ss_lin
	clc
	adc     #$01
	sta     _ss_off
	ldy     #$02
	lda     (c_sp),y
	and     #$03
	sta     _ss_pmg
	jsr     ldax0sp
	jsr     mulax10
	clc
	adc     _sprData
	pha
	txa
	adc     _sprData+1
	tax
	pla
	sec
	sbc     _ss_off
	sta     _ss_src
	txa
	sbc     #$00
	sta     _ss_src+1
	clc
	lda     #$9C
	adc     _ss_pmg
	tax
	lda     #$21
	clc
	adc     _ss_lin
	bcc     L000D
	inx
L000D:	sta     _ss_dst
	stx     _ss_dst+1
	lda     _ss_pmg
	jsr     pusha0
	lda     #$19
	jsr     tosumula0
	clc
	adc     _ss_dli
	sta     _ss_dli
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _sprDrawn,y
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     _ss_dli
	sta     _sprBegDLI,y
	lda     #<(_sprEndDLI)
	ldx     #>(_sprEndDLI)
	ldy     #$02
	clc
	adc     (c_sp),y
	bcc     L0006
	inx
L0006:	sta     ptr1
	stx     ptr1+1
	lda     _ss_dli
	clc
	adc     _sprDLIs
	ldy     #$00
	sta     (ptr1),y
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0012
	inx
	clc
L0012:	adc     #<(_sprSrc)
	sta     ptr1
	txa
	adc     #>(_sprSrc)
	sta     ptr1+1
	lda     _ss_src
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     _ss_src+1
	sta     (ptr1),y
	iny
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0013
	inx
	clc
L0013:	adc     #<(_sprDst)
	sta     ptr1
	txa
	adc     #>(_sprDst)
	sta     ptr1+1
	lda     _ss_dst
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     _ss_dst+1
	sta     (ptr1),y
	iny
	lda     (c_sp),y
	tay
	lda     _ss_off
	sta     _sprLead,y
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     #$01
	sta     _sprDrawn,y
	ldy     #$02
	lda     (c_sp),y
	jsr     _SpriteCollisions
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     _spriteX
	sta     _sprX,y
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     _spriteY
	sta     _sprY,y
	ldy     #$02
	lda     (c_sp),y
	tax
	ldy     #$00
	lda     (c_sp),y
	sta     _sprFrame,x
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     #$01
	sta     _sprDrawn,y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ SpriteCollisions (unsigned char index)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SpriteCollisions: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     _sprCollide,y
	jeq     L0006
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _sprCollision,y
	sta     M0001
L0019:	lda     M0001
	cmp     #$10
	jcs     L0006
	ldy     #$00
	cmp     (c_sp),y
	jeq     L001F
	ldy     M0001
	lda     _sprCollide,y
	jeq     L001F
	ldy     M0001
	lda     _sprY,y
	sec
	sbc     _spriteY
	sta     _sc_dY
	cmp     _cushionLow
	bcc     L001C
	lda     _sc_dY
	cmp     _cushionHigh
	beq     L001F
	bcc     L001F
L001C:	ldy     M0001
	lda     _sprX,y
	sec
	sbc     _spriteX
	sta     _sc_dX
	cmp     _cushionLow
	bcc     L001E
	lda     _sc_dX
	cmp     _cushionHigh
	beq     L001F
	bcc     L001F
L001E:	lda     #<(_sprCollision)
	ldx     #>(_sprCollision)
	ldy     #$00
	clc
	adc     (c_sp),y
	bcc     L0015
	inx
L0015:	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	ldy     M0001
	lda     #$01
	jsr     aslaxy
	and     #$07
	jsr     tosora0
	ldy     #$00
	jsr     staspidx
	lda     #<(_sprCollision)
	ldx     #>(_sprCollision)
	clc
	adc     M0001
	bcc     L0016
	inx
L0016:	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     #$01
	jsr     aslaxy
	and     #$07
	jsr     tosora0
	ldy     #$00
	jsr     staspidx
L001F:	inc     M0001
	jmp     L0019
L0006:	jmp     incsp1

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

