;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_bzero
	.export		_ClearCharmap

; ---------------------------------------------------------------
; void __near__ ClearCharmap (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ClearCharmap: near

.segment	"SHADOW_RAM"

	ldx     #$09
	lda     #$70
	jsr     pushax
	ldx     #$03
	lda     #$E8
	jmp     _bzero

.endproc

