;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_charmapWidth
	.import		_worldX
	.import		_worldY
	.import		_blockWidth
	.import		_charmapData
	.export		_DecodeTiles

; ---------------------------------------------------------------
; unsigned int __near__ DecodeTiles (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_DecodeTiles: near

.segment	"SHADOW_RAM"

	lda     _charmapWidth
	sta     _blockWidth
	lda     _charmapData
	ldx     _charmapData+1
	jsr     pushax
	lda     _charmapWidth
	jsr     pusha0
	lda     _worldY
	jsr     tosumula0
	clc
	adc     _worldX
	bcc     L0002
	inx
L0002:	jmp     tosaddax

.endproc

