;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_BlitCharmap
	.import		_worldX
	.import		_worldY
	.import		_screenData
	.export		_DrawCharmap
	.import		_DecodeTiles

; ---------------------------------------------------------------
; void __near__ DrawCharmap (unsigned char x, unsigned char y)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_DrawCharmap: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	sta     _worldX
	dey
	lda     (c_sp),y
	sta     _worldY
	jsr     _DecodeTiles
	sta     $00E2
	stx     $00E2+1
	lda     _screenData+1
	sta     $00E4+1
	lda     _screenData
	sta     $00E4
	jsr     _BlitCharmap
	jmp     incsp2

.endproc

