;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_free
	.import		_decodeData
	.import		_tilesetData
	.export		_FreeCharmap

; ---------------------------------------------------------------
; void __near__ FreeCharmap (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_FreeCharmap: near

.segment	"SHADOW_RAM"

	lda     _tilesetData
	ora     _tilesetData+1
	beq     L0002
	lda     _tilesetData
	ldx     _tilesetData+1
	jsr     _free
L0002:	lda     _decodeData
	ora     _decodeData+1
	beq     L0003
	lda     _decodeData
	ldx     _decodeData+1
	jmp     _free
L0003:	rts

.endproc

