;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_charflagData
	.import		_GetTile
	.export		_GetFlag

; ---------------------------------------------------------------
; unsigned char __near__ GetFlag (unsigned char x, unsigned char y)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_GetFlag: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     _GetTile
	sta     M0001
	lda     _charflagData
	ldx     _charflagData+1
	ldy     M0001
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

