;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_chrRows
	.import		_bmpRows
	.import		_doubleBuffer
	.import		_bmpAddr
	.export		_charmapWidth
	.export		_charmapHeight
	.export		_worldWidth
	.export		_worldHeight
	.export		_worldX
	.export		_worldY
	.export		_worldMaxX
	.export		_worldMaxY
	.export		_screenCol1
	.export		_screenCol2
	.export		_screenWidth
	.export		_screenRow1
	.export		_screenRow2
	.export		_screenHeight
	.export		_lineBlock
	.export		_blockWidth
	.export		_lineWidth
	.export		_decodeWidth
	.export		_decodeHeight
	.export		_tileX
	.export		_tileY
	.export		_tileCols
	.export		_tileRows
	.export		_scrollCols
	.export		_scrollRows
	.export		_scrollDirX
	.export		_scrollDirY
	.export		_charmapData
	.export		_charflagData
	.export		_decodeData
	.export		_charatrData
	.export		_charsetData
	.export		_screenData
	.export		_tilesetData
	.import		_InitBitmap
	.export		_InitCharmap

.segment	"DATA"

_screenCol1:
	.byte	$00
_screenCol2:
	.byte	$28
_screenWidth:
	.byte	$28
_screenRow1:
	.byte	$00
_screenRow2:
	.byte	$19
_screenHeight:
	.byte	$19
_charmapData:
	.word	$A500
_charatrData:
	.word	$A400
_charflagData:
	.word	$A480
_charsetData:
	.word	$A000

.segment	"BSS"

_charmapWidth:
	.res	1,$00
_charmapHeight:
	.res	1,$00
_worldWidth:
	.res	1,$00
_worldHeight:
	.res	1,$00
_worldX:
	.res	1,$00
_worldY:
	.res	1,$00
_worldMaxX:
	.res	1,$00
_worldMaxY:
	.res	1,$00
_lineBlock:
	.res	1,$00
_blockWidth:
	.res	1,$00
_lineWidth:
	.res	1,$00
_decodeWidth:
	.res	1,$00
_decodeHeight:
	.res	1,$00
_tileX:
	.res	1,$00
_tileY:
	.res	1,$00
_tileCols:
	.res	1,$00
_tileRows:
	.res	1,$00
_scrollCols:
	.res	1,$00
_scrollRows:
	.res	1,$00
_scrollDirX:
	.res	1,$00
_scrollDirY:
	.res	1,$00
_decodeData:
	.res	2,$00
_screenData:
	.res	2,$00
_tilesetData:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ InitCharmap (unsigned char col1, unsigned char col2, unsigned char row1, unsigned char row2)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_InitCharmap: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     #$28
	sta     _lineWidth
	ldy     #$03
	lda     (c_sp),y
	sta     _screenCol1
	dey
	lda     (c_sp),y
	sta     _screenCol2
	dey
	lda     (c_sp),y
	sta     _screenRow1
	dey
	lda     (c_sp),y
	sta     _screenRow2
	ldy     #$02
	lda     (c_sp),y
	sec
	iny
	sbc     (c_sp),y
	sta     _screenWidth
	ldy     #$00
	lda     (c_sp),y
	sec
	iny
	sbc     (c_sp),y
	sta     _screenHeight
	lda     _screenWidth
	sta     _lineBlock
	lda     _screenRow1
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	sta     ptr1
	stx     ptr1+1
	lda     #$70
	clc
	adc     ptr1
	pha
	lda     #$09
	adc     ptr1+1
	tax
	pla
	clc
	adc     _screenCol1
	bcc     L0002
	inx
L0002:	sta     _screenData
	stx     _screenData+1
	jsr     _InitBitmap
	lda     #$00
	sta     _doubleBuffer
	tay
	lda     (c_sp),y
	sta     _chrRows
	ldx     #$00
	lda     (c_sp),y
	ldy     #$C9
	jsr     incaxy
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     shlax3
	jsr     tossubax
	sta     _bmpRows
	ldx     #$00
	lda     (c_sp,x)
	jsr     pusha0
	ldx     #$01
	lda     #$40
	jsr     tosmulax
	sta     ptr1
	stx     ptr1+1
	lda     #$10
	clc
	adc     ptr1
	sta     _bmpAddr
	lda     #$A0
	adc     ptr1+1
	sta     _bmpAddr+1
	jmp     incsp4

.endproc

