;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_malloc
	.import		_screenWidth
	.import		_screenHeight
	.import		_decodeWidth
	.import		_decodeHeight
	.import		_tileCols
	.import		_tileRows
	.import		_decodeData
	.import		_charatrData
	.import		_tilesetData
	.export		_LoadTileset
	.import		_FileOpen
	.import		_FileRead
	.import		_FileClose

; ---------------------------------------------------------------
; void __near__ LoadTileset (char *filename, unsigned int n)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LoadTileset: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     ldax0sp
	sta     M0001
	stx     M0001+1
	lda     #$00
	sta     M0002
	sta     M0002+1
	lda     M0001
	ldx     M0001+1
	jsr     _malloc
	sta     _tilesetData
	stx     _tilesetData+1
	ldy     #$03
	jsr     ldaxysp
	jsr     _FileOpen
	stx     tmp1
	ora     tmp1
	beq     L0006
	lda     _tilesetData
	ldx     _tilesetData+1
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     _FileRead
	jsr     _FileClose
	jmp     L0006
L0003:	lda     _tilesetData
	clc
	adc     M0002
	sta     ptr1
	lda     _tilesetData+1
	adc     M0002+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     M0003
	lda     _tilesetData
	clc
	adc     M0002
	pha
	lda     _tilesetData+1
	adc     M0002+1
	tax
	pla
	sta     ptr2
	stx     ptr2+1
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     sreg
	lda     _charatrData
	ldx     _charatrData+1
	ldy     M0003
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	clc
	adc     sreg
	ldy     #$00
	sta     (ptr2),y
	inc     M0002
	bne     L0006
	inc     M0002+1
L0006:	lda     M0002
	cmp     M0001
	lda     M0002+1
	sbc     M0001+1
	bcc     L0003
	lda     _screenHeight
	clc
	adc     #$01
	sta     _decodeHeight
	lda     _screenWidth
	clc
	adc     #$01
	sta     _decodeWidth
	lda     _decodeHeight
	sta     _tileRows
	lda     _decodeWidth
	sta     _tileCols
	lda     _decodeWidth
	jsr     pusha0
	lda     _decodeHeight
	jsr     tosumula0
	jsr     _malloc
	sta     _decodeData
	stx     _decodeData+1
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00
M0003:
	.res	1,$00

.endproc

