;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_chrPalette
	.import		_charatrData
	.import		_charsetData
	.export		_LoadCharset
	.import		_FileOpen
	.import		_FileRead

; ---------------------------------------------------------------
; void __near__ LoadCharset (char *filename)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LoadCharset: near

.segment	"SHADOW_RAM"

	jsr     pushax
	jsr     ldax0sp
	jsr     _FileOpen
	stx     tmp1
	ora     tmp1
	beq     L0002
	lda     #<(_chrPalette)
	ldx     #>(_chrPalette)
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     _FileRead
	lda     _charsetData
	ldx     _charsetData+1
	jsr     pushax
	ldx     #$04
	lda     #$00
	jsr     _FileRead
	lda     _charatrData
	ldx     _charatrData+1
	jsr     pushax
	ldx     #$01
	lda     #$00
	jsr     _FileRead
L0002:	jmp     incsp2

.endproc

