;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_charmapWidth
	.import		_charmapHeight
	.import		_worldWidth
	.import		_worldHeight
	.import		_worldMaxX
	.import		_worldMaxY
	.import		_screenWidth
	.import		_screenHeight
	.import		_charmapData
	.export		_LoadCharmap
	.import		_FileOpen
	.import		_FileRead
	.import		_FileClose

; ---------------------------------------------------------------
; void __near__ LoadCharmap (char *filename, unsigned int w, unsigned int h)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_LoadCharmap: near

.segment	"SHADOW_RAM"

	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     tosumulax
	sta     M0001
	stx     M0001+1
	ldy     #$02
	lda     (c_sp),y
	sta     _charmapWidth
	ldy     #$00
	lda     (c_sp),y
	sta     _charmapHeight
	ldy     #$02
	lda     (c_sp),y
	sta     _worldWidth
	ldy     #$00
	lda     (c_sp),y
	sta     _worldHeight
	lda     _worldWidth
	sec
	sbc     _screenWidth
	sta     _worldMaxX
	lda     _worldHeight
	sec
	sbc     _screenHeight
	sta     _worldMaxY
	ldy     #$05
	jsr     ldaxysp
	jsr     _FileOpen
	stx     tmp1
	ora     tmp1
	beq     L0002
	lda     _charmapData
	ldx     _charmapData+1
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     _FileRead
	jsr     _FileClose
L0002:	jmp     incsp6

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

