;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_charatrData
	.export		_PrintCharmap

; ---------------------------------------------------------------
; void __near__ PrintCharmap (unsigned char x, unsigned char y, unsigned char chr)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PrintCharmap: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	sta     ptr1
	stx     ptr1+1
	lda     #$70
	clc
	adc     ptr1
	sta     ptr1
	lda     #$09
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0002
	inx
L0002:	sta     sreg
	stx     sreg+1
	lda     _charatrData+1
	sta     ptr1+1
	lda     _charatrData
	sta     ptr1
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	clc
	ldy     #$00
	adc     (c_sp),y
	sta     (sreg),y
	jmp     incsp3

.endproc

