;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_worldX
	.import		_worldY
	.import		_sprDrawn
	.import		_sprFlags
	.import		_sprFrame
	.import		_sprX
	.import		_sprY
	.import		_DrawCharmap
	.export		_ScrollCharmap
	.import		_SetSprite
	.import		_spriteX
	.import		_spriteY
	.export		_stepX
	.export		_stepY
	.export		_ShiftSprites

.segment	"BSS"

_stepX:
	.res	1,$00
_stepY:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ ScrollCharmap (unsigned char x, unsigned char y)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ScrollCharmap: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	sec
	sbc     _worldX
	cmp     #$80
	sta     _stepX
	dey
	lda     (c_sp),y
	sec
	sbc     _worldY
	cmp     #$80
	sta     _stepY
	jsr     _ShiftSprites
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     _DrawCharmap
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ ShiftSprites (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ShiftSprites: near

.segment	"SHADOW_RAM"

	lda     #$00
	sta     M0001
L0010:	lda     M0001
	cmp     #$10
	bcs     L0003
	ldy     M0001
	lda     _sprDrawn,y
	beq     L0011
	ldy     M0001
	lda     _sprFlags,y
	and     #$01
	beq     L0011
	ldy     M0001
	lda     _sprX,y
	jsr     pusha0
	lda     _stepX
	bpl     L000C
	ldx     #$FF
L000C:	jsr     aslax2
	jsr     tossubax
	sta     _spriteX
	ldy     M0001
	lda     _sprY,y
	jsr     pusha0
	lda     _stepY
	bpl     L000E
	ldx     #$FF
L000E:	jsr     aslax3
	jsr     tossubax
	sta     _spriteY
	lda     M0001
	jsr     pusha
	ldy     M0001
	ldx     #$00
	lda     _sprFrame,y
	jsr     _SetSprite
L0011:	inc     M0001
	jmp     L0010
L0003:	rts

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

