;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_charmapWidth
	.import		_charmapData
	.export		_SetTile

; ---------------------------------------------------------------
; void __near__ SetTile (unsigned char x, unsigned char y, unsigned char tile)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_SetTile: near

.segment	"SHADOW_RAM"

	jsr     pusha
	lda     _charmapData
	ldx     _charmapData+1
	jsr     pushax
	lda     _charmapWidth
	jsr     pusha0
	ldy     #$05
	lda     (c_sp),y
	jsr     tosumula0
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0002
	inx
L0002:	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	sta     (ptr1),y
	jmp     incsp3

.endproc

