;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_CharmapDLIST
	.import		_SetPalette
	.import		_chrPalette
	.export		_ShowCharmap

; ---------------------------------------------------------------
; void __near__ ShowCharmap (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_ShowCharmap: near

.segment	"SHADOW_RAM"

	jsr     _CharmapDLIST
	lda     $022F
	ora     #$20
	sta     $022F
	lda     #<(_chrPalette)
	ldx     #>(_chrPalette)
	jmp     _SetPalette

.endproc

