;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_fileNum
	.export		_fileNames
	.export		_fileSizes
	.export		_fileBuffer
	.import		_xbios_list_dir
	.import		_xbios_get_entry
	.export		_DirList

.segment	"BSS"

_fileNum:
	.res	1,$00
_fileNames:
	.res	48,$00
_fileSizes:
	.res	48,$00
_fileBuffer:
	.res	312,$00

; ---------------------------------------------------------------
; void __near__ DirList (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_DirList: near

.segment	"SHADOW_RAM"

	lda     #$00
	sta     M0002
	jsr     _xbios_list_dir
	jsr     _xbios_get_entry
	sta     M0001
	jmp     L0004
L001D:	lda     _fileNum
	asl     a
	bcc     L001B
	ldx     #$01
	clc
L001B:	adc     #<(_fileNames)
	sta     ptr1
	txa
	adc     #>(_fileNames)
	sta     ptr1+1
	lda     #<(_fileBuffer)
	ldx     #>(_fileBuffer)
	clc
	adc     M0002
	bcc     L0009
	inx
L0009:	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	lda     _fileNum
	asl     a
	bcc     L001C
	inx
	clc
L001C:	adc     #<(_fileSizes)
	sta     sreg
	txa
	adc     #>(_fileSizes)
	sta     sreg+1
	ldx     #$03
	lda     #$FC
	clc
	adc     M0001
	bcc     L0024
	inx
L0024:	jsr     ldaxi
	tax
	lda     #$00
	tay
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
	lda     #$00
	sta     M0003
	jmp     L001F
L000B:	ldx     #$04
	clc
	lda     M0001
	bcc     L000F
	inx
L000F:	ldy     M0003
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$20
	beq     L001E
	lda     M0002
	inc     M0002
	clc
	adc     #<(_fileBuffer)
	sta     sreg
	lda     #$00
	adc     #>(_fileBuffer)
	sta     sreg+1
	ldx     #$04
	clc
	lda     M0001
	bcc     L0010
	inx
L0010:	ldy     M0003
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
L001E:	inc     M0003
L001F:	lda     M0003
	cmp     #$08
	bcc     L000B
	lda     M0002
	inc     M0002
	clc
	adc     #<(_fileBuffer)
	sta     ptr1
	lda     #$00
	adc     #>(_fileBuffer)
	sta     ptr1+1
	lda     #$2E
	ldy     #$00
	sta     (ptr1),y
	jmp     L0021
L0020:	lda     M0002
	inc     M0002
	clc
	adc     #<(_fileBuffer)
	sta     sreg
	lda     #$00
	adc     #>(_fileBuffer)
	sta     sreg+1
	ldx     #$04
	clc
	lda     M0001
	bcc     L0014
	inx
L0014:	ldy     M0003
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0003
L0021:	lda     M0003
	cmp     #$0B
	bcc     L0020
	lda     M0002
	inc     M0002
	clc
	adc     #<(_fileBuffer)
	sta     ptr1
	tya
	adc     #>(_fileBuffer)
	sta     ptr1+1
	tya
	sta     (ptr1),y
	jsr     _xbios_get_entry
	sta     M0001
	inc     _fileNum
L0004:	lda     _fileNum
	cmp     #$18
	bcs     L0022
	ldy     M0001
	ldx     #$00
	lda     $0400,y
	jne     L001D
L0022:	rts

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00

.endproc

