;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_doubleBuffer
	.export		_SetPalette

.segment	"BSS"

_doubleBuffer:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ SetPalette (unsigned char *palette)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SetPalette: near

.segment	"CODE"

	jsr     pushax
	jsr     ldptr10sp
	ldy     #$00
	lda     (ptr1),y
	sta     $02C8
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $02C4
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $02C5
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $02C6
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $02C7
	jmp     incsp2

.endproc

