;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_xbios_open_file
	.import		_xbios_load_data
	.import		_xbios_fname
	.import		_xbios_dest
	.import		_xbios_len
	.export		_FileSet
	.export		_FileOpen
	.export		_FileRead
	.export		_FileClose

; ---------------------------------------------------------------
; void __near__ FileSet (const char *fname)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_FileSet: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     M0001
	sta     M0002
	jmp     L0017
L0002:	jsr     ldax0sp
	ldy     M0002
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$2E
	beq     L0005
	jsr     ldax0sp
	ldy     M0002
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$61
	bcc     L0006
	lda     M0001
	inc     M0001
	clc
	adc     _xbios_fname
	ldx     _xbios_fname+1
	bcc     L0011
	inx
L0011:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     M0002
	inc     M0002
	clc
	ldy     #$00
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     (ptr1,x)
	ldy     #$20
	jsr     decaxy
	ldy     #$00
	sta     (sreg),y
	jmp     L0017
L0006:	lda     M0001
	inc     M0001
	clc
	adc     _xbios_fname
	ldx     _xbios_fname+1
	bcc     L0012
	inx
L0012:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     M0002
	inc     M0002
	clc
	ldy     #$00
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	dey
	lda     (ptr1),y
	sta     (sreg),y
	jmp     L0017
L0005:	lda     M0001
	inc     M0001
	clc
	adc     _xbios_fname
	ldx     _xbios_fname+1
	bcc     L0013
	inx
L0013:	sta     ptr1
	stx     ptr1+1
	lda     #$20
	ldy     #$00
	sta     (ptr1),y
L0017:	lda     M0001
	cmp     #$08
	jcc     L0002
	inc     M0002
	jmp     L0018
L0009:	jsr     ldax0sp
	ldy     M0002
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$61
	bcc     L000C
	lda     M0001
	inc     M0001
	clc
	adc     _xbios_fname
	ldx     _xbios_fname+1
	bcc     L0014
	inx
L0014:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     M0002
	inc     M0002
	clc
	ldy     #$00
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     (ptr1,x)
	ldy     #$20
	jsr     decaxy
	ldy     #$00
	jmp     L0016
L000C:	lda     M0001
	inc     M0001
	clc
	adc     _xbios_fname
	ldx     _xbios_fname+1
	bcc     L0015
	inx
L0015:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     M0002
	inc     M0002
	clc
	ldy     #$00
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	dey
	lda     (ptr1),y
L0016:	sta     (sreg),y
L0018:	lda     M0001
	cmp     #$0B
	bcc     L0009
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ FileOpen (const char *fname)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_FileOpen: near

.segment	"CODE"

	jsr     pushax
	jsr     ldax0sp
	jsr     _FileSet
	jsr     _xbios_open_file
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ FileRead (char *buffer, int len)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_FileRead: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	sta     _xbios_dest
	stx     _xbios_dest+1
	jsr     ldax0sp
	sta     _xbios_len
	stx     _xbios_len+1
	jsr     _xbios_load_data
	jsr     ldax0sp
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ FileClose (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_FileClose: near

.segment	"CODE"

	rts

.endproc

