;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_collideEnabled
	.import		_EnableSprite
	.import		_DisableSprite
	.import		_SetSprite
	.export		_EnableMultiColorSprite
	.export		_DisableMultiColorSprite
	.export		_SetMultiColorSprite
	.export		_DoubleWidthSprite

; ---------------------------------------------------------------
; void __near__ EnableMultiColorSprite (unsigned char index)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EnableMultiColorSprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	pha
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	pla
	jsr     _EnableSprite
	lda     #$00
	sta     _collideEnabled
	tay
	lda     (c_sp),y
	jsr     _EnableSprite
	lda     #$01
	sta     _collideEnabled
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ DisableMultiColorSprite (unsigned char index)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisableMultiColorSprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	pha
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	pla
	jsr     _DisableSprite
	ldy     #$00
	lda     (c_sp),y
	jsr     _DisableSprite
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ SetMultiColorSprite (unsigned char index, unsigned int frame)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SetMultiColorSprite: near

.segment	"CODE"

	jsr     pushax
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	dey
	jsr     ldaxysp
	jsr     _SetSprite
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	ldy     #$12
	jsr     incaxy
	jsr     _SetSprite
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ DoubleWidthSprite (unsigned char index, unsigned char onoff)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DoubleWidthSprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	beq     L0002
	iny
	lda     (c_sp),y
	tay
	lda     #$01
	jmp     L0006
L0002:	iny
	lda     (c_sp),y
	tay
	lda     #$00
L0006:	sta     $D008,y
	jmp     incsp2

.endproc

