;
; File generated by cc65 v 2.19 - Git f54780cfb
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780cfb"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_StopMusic
	.export		_InitSFX
	.export		_StopSFX
	.export		_PlaySFX
	.export		_sfxData
	.import		_SetupSFX
	.import		_sampleTimer
	.import		_sampleFreq
	.import		_sampleCtrl

.segment	"DATA"

_sfxData:
	.byte	$18
	.byte	$A0
	.byte	$08
	.byte	$C0
	.byte	$FF
	.byte	$A0
	.byte	$02
	.byte	$E0
	.byte	$04
	.byte	$80
	.byte	$FF
	.byte	$C0

; ---------------------------------------------------------------
; void __near__ InitSFX (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_InitSFX: near

.segment	"SHADOW_RAM"

	jmp     _SetupSFX

.endproc

; ---------------------------------------------------------------
; void __near__ StopSFX (void)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_StopSFX: near

.segment	"SHADOW_RAM"

	jsr     _StopMusic
	lda     #$00
	sta     M0001
L0009:	lda     M0001
	cmp     #$02
	bcs     L0003
	ldy     M0001
	lda     #$00
	sta     _sampleTimer,y
	tax
	lda     M0001
	asl     a
	bcc     L0007
	inx
L0007:	sta     ptr1
	stx     ptr1+1
	clc
	lda     #$D2
	adc     ptr1+1
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	tax
	lda     M0001
	asl     a
	bcc     L0008
	inx
L0008:	sta     ptr1
	stx     ptr1+1
	lda     #$01
	clc
	adc     ptr1
	sta     ptr1
	lda     #$D2
	adc     ptr1+1
	sta     ptr1+1
	tya
	sta     (ptr1),y
	inc     M0001
	jmp     L0009
L0003:	rts

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ PlaySFX (unsigned char index, unsigned char pitch, unsigned char volume, unsigned char channel)
; ---------------------------------------------------------------

.segment	"SHADOW_RAM"

.proc	_PlaySFX: near

.segment	"SHADOW_RAM"

	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0006
	inx
	clc
L0006:	adc     #<(_sfxData)
	sta     M0001
	txa
	adc     #>(_sfxData)
	sta     M0001+1
	lda     #<(_sampleTimer)
	ldx     #>(_sampleTimer)
	ldy     #$00
	clc
	adc     (c_sp),y
	bcc     L0002
	inx
L0002:	sta     sreg
	stx     sreg+1
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     (ptr1),y
	sta     (sreg),y
	lda     #<(_sampleFreq)
	ldx     #>(_sampleFreq)
	clc
	adc     (c_sp),y
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	eor     #$FF
	ldy     #$00
	sta     (ptr1),y
	lda     #<(_sampleCtrl)
	ldx     #>(_sampleCtrl)
	clc
	adc     (c_sp),y
	bcc     L0004
	inx
L0004:	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	ldy     #$05
	lda     (c_sp),y
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	jsr     tosora0
	ldy     #$00
	jsr     staspidx
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	2,$00

.endproc

